/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.JPanel;

/**
 *
 * @author ferchs
 */
public class AdministrarGradosPanel extends javax.swing.JPanel {

    private RecursosPanel recursosPanel;
    private JPanel actual;
    
    /**
     * Creates new form AdministrarSalones
     */
    public AdministrarGradosPanel(RecursosPanel recursosPanel) {
        initComponents();
        this.recursosPanel=recursosPanel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelLogo1 = new javax.swing.JPanel();
        agregarGrado = new javax.swing.JButton();
        agregarSalonText = new javax.swing.JLabel();
        inicio = new javax.swing.JButton();
        inicioText = new javax.swing.JLabel();
        buscar = new javax.swing.JButton();
        buscarText = new javax.swing.JLabel();

        setBackground(new java.awt.Color(102, 102, 102));
        setForeground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelLogo1.setBackground(new java.awt.Color(101, 166, 148));
        PanelLogo1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        agregarGrado.setBackground(new java.awt.Color(102, 102, 102));
        agregarGrado.setForeground(new java.awt.Color(255, 255, 255));
        agregarGrado.setIcon(new javax.swing.ImageIcon("/Users/ferchs/Desktop/MasMini.png")); // NOI18N
        agregarGrado.setBorderPainted(false);
        agregarGrado.setOpaque(true);
        agregarGrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarGradoActionPerformed(evt);
            }
        });
        PanelLogo1.add(agregarGrado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 60, -1));

        agregarSalonText.setBackground(new java.awt.Color(255, 255, 255));
        agregarSalonText.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        agregarSalonText.setForeground(new java.awt.Color(255, 255, 255));
        agregarSalonText.setText("<html>\n<pre>Agregar\n Grado</pre>\n</html>");
        PanelLogo1.add(agregarSalonText, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        inicio.setBackground(new java.awt.Color(102, 102, 102));
        inicio.setForeground(new java.awt.Color(255, 255, 255));
        inicio.setIcon(new javax.swing.ImageIcon("/Users/ferchs/Desktop/inicio.png")); // NOI18N
        inicio.setBorderPainted(false);
        inicio.setOpaque(true);
        inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inicioActionPerformed(evt);
            }
        });
        PanelLogo1.add(inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 510, 60, -1));

        inicioText.setBackground(new java.awt.Color(255, 255, 255));
        inicioText.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        inicioText.setForeground(new java.awt.Color(255, 255, 255));
        inicioText.setText("inicio");
        PanelLogo1.add(inicioText, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 560, -1, -1));

        buscar.setBackground(new java.awt.Color(102, 102, 102));
        buscar.setForeground(new java.awt.Color(255, 255, 255));
        buscar.setIcon(new javax.swing.ImageIcon("/Users/ferchs/Desktop/buscar.png")); // NOI18N
        buscar.setBorderPainted(false);
        buscar.setOpaque(true);
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });
        PanelLogo1.add(buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 60, -1));

        buscarText.setBackground(new java.awt.Color(255, 255, 255));
        buscarText.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        buscarText.setForeground(new java.awt.Color(255, 255, 255));
        buscarText.setText("Buscar");
        PanelLogo1.add(buscarText, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        add(PanelLogo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, 580));
    }// </editor-fold>//GEN-END:initComponents

    private void agregarGradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarGradoActionPerformed
        // TODO add your handling code here:
        AgregarGradoPanel agregarGradoPanel=new AgregarGradoPanel();
        mostarPanel(agregarGradoPanel);
    }//GEN-LAST:event_agregarGradoActionPerformed

    private void inicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inicioActionPerformed
        // TODO add your handling code here:
        recursosPanel.mostrarInicio();
    }//GEN-LAST:event_inicioActionPerformed

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        // TODO add your handling code here:
       BuscarGradoPanel buscarGradoPanel=new BuscarGradoPanel(this);
       mostarPanel(buscarGradoPanel);
    }//GEN-LAST:event_buscarActionPerformed

    public void mostarPanel(JPanel panel){
        if(actual!=null){
            remove(actual);
        }
        actual=panel;
        add(panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 810, 580));
        revalidate();
        repaint();
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelLogo1;
    private javax.swing.JButton agregarGrado;
    private javax.swing.JLabel agregarSalonText;
    private javax.swing.JButton buscar;
    private javax.swing.JLabel buscarText;
    private javax.swing.JButton inicio;
    private javax.swing.JLabel inicioText;
    // End of variables declaration//GEN-END:variables
}
