/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import com.mysql.jdbc.exceptions.MySQLIntegrityConstraintViolationException;
import control.ControlAdministrarCursos;
import control.ControlGestionarEvaluaciones;
import java.awt.Color;
import java.awt.event.ItemEvent;
import java.util.HashMap;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;



/**
 *
 * @author ferchs
 */
public class AgregarEvaluacionPanel extends javax.swing.JPanel {

    /**
     * Creates new form AgregarEstudiantePanel
     */
    public AgregarEvaluacionPanel() {
      controlAdministrarCursos= new ControlAdministrarCursos();
      controlGestionarEvaluaciones= new ControlGestionarEvaluaciones();
      initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelInformacionCurso = new javax.swing.JPanel();
        temaT = new javax.swing.JLabel();
        gradoT = new javax.swing.JLabel();
        consecutivo = new javax.swing.JComboBox<>();
        consecutivoT = new javax.swing.JLabel();
        materia = new javax.swing.JComboBox<>();
        grado = new javax.swing.JComboBox<>();
        materiaT = new javax.swing.JLabel();
        tema = new javax.swing.JTextField();
        porcentajeT = new javax.swing.JLabel();
        porcentaje = new javax.swing.JTextField();
        guardar = new javax.swing.JButton();

        setBackground(new java.awt.Color(102, 102, 102));
        setForeground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelInformacionCurso.setBackground(new java.awt.Color(102, 102, 102));
        panelInformacionCurso.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Informacion de la evaluacion", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 0, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        panelInformacionCurso.setForeground(new java.awt.Color(255, 255, 255));
        panelInformacionCurso.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        temaT.setBackground(new java.awt.Color(255, 255, 255));
        temaT.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        temaT.setForeground(new java.awt.Color(255, 255, 255));
        temaT.setText("Tema:");
        panelInformacionCurso.add(temaT, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, -1, -1));

        gradoT.setBackground(new java.awt.Color(255, 255, 255));
        gradoT.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        gradoT.setForeground(new java.awt.Color(255, 255, 255));
        gradoT.setText("Grado:");
        panelInformacionCurso.add(gradoT, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, -1, -1));

        consecutivo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione...", "1", "2", "3", "4", "5" }));
        consecutivo.setEnabled(false);
        consecutivo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                consecutivoItemStateChanged(evt);
            }
        });
        panelInformacionCurso.add(consecutivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, -1, -1));

        consecutivoT.setBackground(new java.awt.Color(255, 255, 255));
        consecutivoT.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        consecutivoT.setForeground(new java.awt.Color(255, 255, 255));
        consecutivoT.setText("Consecutivo:");
        panelInformacionCurso.add(consecutivoT, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, -1, -1));

        materia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione..." }));
        materia.setEnabled(false);
        panelInformacionCurso.add(materia, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, -1, -1));

        grado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione...", "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        cargarGrados();
        grado.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                gradoItemStateChanged(evt);
            }
        });
        panelInformacionCurso.add(grado, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, -1, -1));

        materiaT.setBackground(new java.awt.Color(255, 255, 255));
        materiaT.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        materiaT.setForeground(new java.awt.Color(255, 255, 255));
        materiaT.setText("Materia:");
        panelInformacionCurso.add(materiaT, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, -1, -1));
        panelInformacionCurso.add(tema, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 300, -1));

        porcentajeT.setBackground(new java.awt.Color(255, 255, 255));
        porcentajeT.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        porcentajeT.setForeground(new java.awt.Color(255, 255, 255));
        porcentajeT.setText("Porcentaje:");
        panelInformacionCurso.add(porcentajeT, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, 90, -1));

        porcentaje.setForeground(new java.awt.Color(204, 204, 204));
        porcentaje.setText("Ej: 100");
        porcentaje.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                porcentajeMouseClicked(evt);
            }
        });
        panelInformacionCurso.add(porcentaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, 100, -1));

        add(panelInformacionCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 460, 370));

        guardar.setBackground(new java.awt.Color(101, 166, 148));
        guardar.setForeground(new java.awt.Color(255, 255, 255));
        guardar.setText("Guardar");
        guardar.setBorderPainted(false);
        guardar.setOpaque(true);
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });
        add(guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 460, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
        // TODO add your handling code here:
        boolean validos=validarCamposPanel();
        if(validos){
            String gradoStr=(String) grado.getSelectedItem();
            String consecutivoStr=(String) consecutivo.getSelectedItem();
            int consecutivoTmp=Integer.parseInt(consecutivoStr);
            HashMap<String,String> datosCurso=controlAdministrarCursos.obtenerDatosCurso(gradoStr, consecutivoTmp);
            int idGrado=Integer.parseInt(datosCurso.get("idGrado"));
            String item=(String)materia.getSelectedItem();
            int index=item.indexOf("-");
            String tmp=item.substring(index+1,item.length()).trim();
            int idMateria=Integer.parseInt(tmp);
            String temaTmp= tema.getText().trim();
            double porcentajeTmp=obternerPorcentaje(porcentaje.getText());
            try{
                controlGestionarEvaluaciones.crearEvaluacion(idGrado, consecutivoTmp, idMateria, temaTmp, porcentajeTmp);   
            }
            catch(MySQLIntegrityConstraintViolationException e){
                JOptionPane mensaje= new JOptionPane();
                mensaje.setBackground(new java.awt.Color(102, 102, 102));
                mensaje.setForeground(Color.white);
                mensaje.showMessageDialog(null,"Ya existe una evaluacion creada con este Tema");
            limpiarCampos();
            }
            JOptionPane mensaje= new JOptionPane();
            mensaje.setBackground(new java.awt.Color(102, 102, 102));
            mensaje.setForeground(Color.white);
            mensaje.showMessageDialog(null,"Se ha registrado una nueva evaluacion");
            limpiarCampos();
        }
        else{
            JOptionPane mensaje= new JOptionPane();
            mensaje.setBackground(new java.awt.Color(102, 102, 102));
            mensaje.setForeground(Color.white);
            mensaje.showMessageDialog(null,"Debes completar los campos indicados");
        }
    }//GEN-LAST:event_guardarActionPerformed

    private double obternerPorcentaje(String porcentaje){
        float porcent=Float.parseFloat(porcentaje);
        double resultado=porcent/100;
        return resultado;
    }
    
    private void gradoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_gradoItemStateChanged
        // TODO add your handling code here:
        if(evt.getStateChange()==ItemEvent.SELECTED){
            if(grado.getSelectedIndex()>0){
                String nombreGrado=(String) grado.getSelectedItem();
                String [] listadoConsecutivos=controlGestionarEvaluaciones.obtenerConsecutivosGradosImpartidos(nombreGrado);
                if(listadoConsecutivos!=null){
                    listadoConsecutivos[0]="Seleccione...";
                    DefaultComboBoxModel consecutivos= new DefaultComboBoxModel(listadoConsecutivos);
                    consecutivo.setModel(consecutivos);
                    consecutivo.setEnabled(true);
                }
                else{
                    JOptionPane mensaje= new JOptionPane();
                    mensaje.setBackground(new java.awt.Color(102, 102, 102));
                    mensaje.setForeground(Color.white);
                    mensaje.showMessageDialog(null,"No existen cursos creados para el grado "+nombreGrado);
                }
            }
            else{
                consecutivo.setEnabled(false);
                consecutivo.setSelectedIndex(0);
                materia.setEnabled(false);
                materia.setSelectedIndex(0);
            }
        }
    }//GEN-LAST:event_gradoItemStateChanged

    private void consecutivoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_consecutivoItemStateChanged
        // TODO add your handling code here:
        int itemIndex=consecutivo.getSelectedIndex();
        if(itemIndex>0){
             String nombreGrado=(String) grado.getSelectedItem();
             String consecutivoStr= (String) consecutivo.getSelectedItem();
             int consecutivo=Integer.parseInt(consecutivoStr);
             HashMap<String,String> datosCurso=controlAdministrarCursos.obtenerDatosCurso(nombreGrado, consecutivo);
             int idGrado=Integer.parseInt(datosCurso.get("idGrado"));
             String [] listadoMaterias=controlGestionarEvaluaciones.obtenerMateriasGradosImpartidos(idGrado,consecutivo);
             if(listadoMaterias.length>0){
                listadoMaterias[0]="Seleccione...";
                DefaultComboBoxModel materias= new DefaultComboBoxModel(listadoMaterias);
                materia.setModel(materias);
                materia.setEnabled(true);
             }
        }
    }//GEN-LAST:event_consecutivoItemStateChanged

    private void porcentajeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_porcentajeMouseClicked
        // TODO add your handling code here:
        porcentaje.setForeground(new java.awt.Color(0, 0, 0));
        porcentaje.setText("");
    }//GEN-LAST:event_porcentajeMouseClicked

    private boolean validarCamposPanel( ){
        boolean datosCompletos=true;
      if(grado.getSelectedIndex()==0){
          gradoT.setForeground(Color.red);
          datosCompletos=false;
      }
      else{
          gradoT.setForeground(Color.WHITE);
      }
      if(consecutivo.getSelectedIndex()==0){
          consecutivoT.setForeground(Color.red);
          datosCompletos=false;
      }
      else{
        consecutivoT.setForeground(Color.WHITE);
      }
      if(materia.getSelectedIndex()==0){
          materiaT.setForeground(Color.red);
          datosCompletos=false;
      }
      else{
          materiaT.setForeground(Color.WHITE);
      }
      if(tema.getText().isEmpty()){
          temaT.setForeground(Color.red);
          datosCompletos=false;
      }
      else{
          temaT.setForeground(Color.WHITE);
      }
      if(porcentaje.getText().isEmpty()){
          porcentajeT.setForeground(Color.red);
          datosCompletos=false;
      }
      else{
          porcentajeT.setForeground(Color.WHITE);
      }
      return datosCompletos;
    }
    
    private void limpiarCampos(){
        grado.setSelectedIndex(0);
        gradoT.setForeground(Color.WHITE);
        consecutivo.setSelectedIndex(0);
        consecutivoT.setForeground(Color.WHITE);
        materia.setSelectedIndex(0);
        materiaT.setForeground(Color.WHITE);
        tema.setText("");
        temaT.setForeground(Color.WHITE);
        porcentaje.setText("");
        porcentajeT.setForeground(Color.WHITE);
    }
    
    
    private final void cargarGrados(){
        String [] listadoGrados=controlGestionarEvaluaciones.obtenerGradosImpartidos();
        if(listadoGrados!=null){
        listadoGrados[0]="Seleccione...";
        DefaultComboBoxModel grados= new DefaultComboBoxModel(listadoGrados);
        grado.setModel(grados);
        }
        else{
            listadoGrados=new String[1];
            listadoGrados[0]="Seleccione...";
            DefaultComboBoxModel grados= new DefaultComboBoxModel(listadoGrados);
            grado.setModel(grados);
        }
    }
    
    private ControlGestionarEvaluaciones controlGestionarEvaluaciones;
    private ControlAdministrarCursos controlAdministrarCursos;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> consecutivo;
    private javax.swing.JLabel consecutivoT;
    private javax.swing.JComboBox<String> grado;
    private javax.swing.JLabel gradoT;
    private javax.swing.JButton guardar;
    private javax.swing.JComboBox<String> materia;
    private javax.swing.JLabel materiaT;
    private javax.swing.JPanel panelInformacionCurso;
    private javax.swing.JTextField porcentaje;
    private javax.swing.JLabel porcentajeT;
    private javax.swing.JTextField tema;
    private javax.swing.JLabel temaT;
    // End of variables declaration//GEN-END:variables
}
