/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import control.ControlAgregarEstudiantePanel;
import java.awt.Color;
import java.awt.event.ItemEvent;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;


/**
 *
 * @author ferchs
 */
public class AgregarEstudiantePanel extends javax.swing.JPanel {

    /**
     * Creates new form AgregarEstudiantePanel
     */
    public AgregarEstudiantePanel() {
        controlAgregarEstudiantePanel= new ControlAgregarEstudiantePanel();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelDatosFamiliar = new javax.swing.JPanel();
        idFamiliar = new javax.swing.JTextField();
        idFamiliarT = new javax.swing.JLabel();
        primerNombreFamiliarT = new javax.swing.JLabel();
        primerNombreFamiliar = new javax.swing.JTextField();
        segundoNombreFamiliarT = new javax.swing.JLabel();
        segundoNombreFamiliar = new javax.swing.JTextField();
        primerApellidoFamiliarT = new javax.swing.JLabel();
        primerApellidoFamiliar = new javax.swing.JTextField();
        segundoApellidoFamiliarT = new javax.swing.JLabel();
        segundoApellidoFamiliar = new javax.swing.JTextField();
        tipoDocumentoFamiliarT = new javax.swing.JLabel();
        tipoDocumentoFamiliar = new javax.swing.JComboBox<>();
        profesionFamiliarT = new javax.swing.JLabel();
        profesionFamiliar = new javax.swing.JTextField();
        parentescoFamiliarT = new javax.swing.JLabel();
        parentescoFamiliar = new javax.swing.JTextField();
        panelDatosContacto = new javax.swing.JPanel();
        direccionEstudianteT = new javax.swing.JLabel();
        direccionEstudiante = new javax.swing.JTextField();
        barrioEstudianteT = new javax.swing.JLabel();
        barrioEstudiante = new javax.swing.JTextField();
        correoEstudiante = new javax.swing.JTextField();
        correoEstudianteT = new javax.swing.JLabel();
        telefonoEstudianteT = new javax.swing.JLabel();
        celularEstudianteT = new javax.swing.JLabel();
        telefonoEstudiante = new javax.swing.JTextField();
        celularEstudiante = new javax.swing.JTextField();
        guardar = new javax.swing.JButton();
        panelInformacionEstudiante = new javax.swing.JPanel();
        primerNombreEstudianteT = new javax.swing.JLabel();
        primerNombreEstudiante = new javax.swing.JTextField();
        segundoNombreEstudianteT = new javax.swing.JLabel();
        segundoNombreEstudiante = new javax.swing.JTextField();
        primerApellidoEstudianteT = new javax.swing.JLabel();
        primerApellidoEstudiante = new javax.swing.JTextField();
        segundoApellidoEstudianteT = new javax.swing.JLabel();
        segundoApellidoEstudiante = new javax.swing.JTextField();
        sexoEstudianteT = new javax.swing.JLabel();
        sexoEstudiante = new javax.swing.JComboBox<>();
        rhEstudianteT = new javax.swing.JLabel();
        rhEstudiante = new javax.swing.JComboBox<>();
        paisEstudianteT = new javax.swing.JLabel();
        paisEstudiante = new javax.swing.JComboBox<>();
        fechaNacimientoT = new javax.swing.JLabel();
        estratoEstudianteT = new javax.swing.JLabel();
        estratoEstudiante = new javax.swing.JComboBox<>();
        fechaNacimiento = new com.toedter.calendar.JDateChooser();
        lugarNacimientoEstudianteT = new javax.swing.JLabel();
        lugarNacimientoEstudiante = new javax.swing.JTextField();
        idEstudiante = new javax.swing.JTextField();
        idEstudianteT = new javax.swing.JLabel();
        tipoDocumentoEstudianteT = new javax.swing.JLabel();
        tipoDocumentoEstudiante = new javax.swing.JComboBox<>();
        panelDatosMedicos = new javax.swing.JPanel();
        nombreSaludEstudianteT = new javax.swing.JLabel();
        nombreSaludEstudiante = new javax.swing.JTextField();
        tipoSaludT = new javax.swing.JLabel();
        tipoSalud = new javax.swing.JComboBox<>();
        nivelSisbenT = new javax.swing.JLabel();
        nivelSisben = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(102, 102, 102));
        setForeground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelDatosFamiliar.setBackground(new java.awt.Color(102, 102, 102));
        panelDatosFamiliar.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos Familiar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 0, 13), new java.awt.Color(255, 255, 255))); // NOI18N
        panelDatosFamiliar.setForeground(new java.awt.Color(255, 255, 255));
        panelDatosFamiliar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        idFamiliar.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        panelDatosFamiliar.add(idFamiliar, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 47, 216, -1));

        idFamiliarT.setBackground(new java.awt.Color(255, 255, 255));
        idFamiliarT.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        idFamiliarT.setForeground(new java.awt.Color(255, 255, 255));
        idFamiliarT.setText("Numero Identificación:");
        panelDatosFamiliar.add(idFamiliarT, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 26, -1, -1));

        primerNombreFamiliarT.setBackground(new java.awt.Color(255, 255, 255));
        primerNombreFamiliarT.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        primerNombreFamiliarT.setForeground(new java.awt.Color(255, 255, 255));
        primerNombreFamiliarT.setText("Primer Nombre:");
        panelDatosFamiliar.add(primerNombreFamiliarT, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 76, -1, -1));

        primerNombreFamiliar.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        panelDatosFamiliar.add(primerNombreFamiliar, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 97, 216, -1));

        segundoNombreFamiliarT.setBackground(new java.awt.Color(255, 255, 255));
        segundoNombreFamiliarT.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        segundoNombreFamiliarT.setForeground(new java.awt.Color(255, 255, 255));
        segundoNombreFamiliarT.setText("Segundo Nombre:");
        panelDatosFamiliar.add(segundoNombreFamiliarT, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 76, -1, -1));

        segundoNombreFamiliar.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        panelDatosFamiliar.add(segundoNombreFamiliar, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 97, 216, -1));

        primerApellidoFamiliarT.setBackground(new java.awt.Color(255, 255, 255));
        primerApellidoFamiliarT.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        primerApellidoFamiliarT.setForeground(new java.awt.Color(255, 255, 255));
        primerApellidoFamiliarT.setText("Primer Apellido:");
        panelDatosFamiliar.add(primerApellidoFamiliarT, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 132, -1, -1));

        primerApellidoFamiliar.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        panelDatosFamiliar.add(primerApellidoFamiliar, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 153, 216, -1));

        segundoApellidoFamiliarT.setBackground(new java.awt.Color(255, 255, 255));
        segundoApellidoFamiliarT.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        segundoApellidoFamiliarT.setForeground(new java.awt.Color(255, 255, 255));
        segundoApellidoFamiliarT.setText("Segundo Apellido:");
        panelDatosFamiliar.add(segundoApellidoFamiliarT, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 132, -1, -1));

        segundoApellidoFamiliar.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        panelDatosFamiliar.add(segundoApellidoFamiliar, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 153, 216, -1));

        tipoDocumentoFamiliarT.setBackground(new java.awt.Color(255, 255, 255));
        tipoDocumentoFamiliarT.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        tipoDocumentoFamiliarT.setForeground(new java.awt.Color(255, 255, 255));
        tipoDocumentoFamiliarT.setText("Tipo:");
        panelDatosFamiliar.add(tipoDocumentoFamiliarT, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 24, -1, -1));

        tipoDocumentoFamiliar.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        tipoDocumentoFamiliar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione...", "Tarjeta Identidad", "Cedula Ciudadania", "Cedula Extranjeria", "Registro Civil", " " }));
        panelDatosFamiliar.add(tipoDocumentoFamiliar, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 45, -1, -1));

        profesionFamiliarT.setBackground(new java.awt.Color(255, 255, 255));
        profesionFamiliarT.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        profesionFamiliarT.setForeground(new java.awt.Color(255, 255, 255));
        profesionFamiliarT.setText("Profesion:");
        panelDatosFamiliar.add(profesionFamiliarT, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 178, -1, -1));

        profesionFamiliar.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        panelDatosFamiliar.add(profesionFamiliar, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 197, 216, -1));

        parentescoFamiliarT.setBackground(new java.awt.Color(255, 255, 255));
        parentescoFamiliarT.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        parentescoFamiliarT.setForeground(new java.awt.Color(255, 255, 255));
        parentescoFamiliarT.setText("Parentesco:");
        panelDatosFamiliar.add(parentescoFamiliarT, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 178, -1, -1));

        parentescoFamiliar.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        panelDatosFamiliar.add(parentescoFamiliar, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 197, 216, -1));

        add(panelDatosFamiliar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 460, 230));

        panelDatosContacto.setBackground(new java.awt.Color(102, 102, 102));
        panelDatosContacto.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos De Contacto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 0, 13), new java.awt.Color(255, 255, 255))); // NOI18N
        panelDatosContacto.setForeground(new java.awt.Color(255, 255, 255));
        panelDatosContacto.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        direccionEstudianteT.setBackground(new java.awt.Color(255, 255, 255));
        direccionEstudianteT.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        direccionEstudianteT.setForeground(new java.awt.Color(255, 255, 255));
        direccionEstudianteT.setText("Dirección:");
        panelDatosContacto.add(direccionEstudianteT, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 24, -1, -1));

        direccionEstudiante.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        direccionEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                direccionEstudianteActionPerformed(evt);
            }
        });
        panelDatosContacto.add(direccionEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 45, 296, -1));

        barrioEstudianteT.setBackground(new java.awt.Color(255, 255, 255));
        barrioEstudianteT.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        barrioEstudianteT.setForeground(new java.awt.Color(255, 255, 255));
        barrioEstudianteT.setText("Barrio:");
        panelDatosContacto.add(barrioEstudianteT, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 76, -1, -1));

        barrioEstudiante.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        panelDatosContacto.add(barrioEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 95, 296, -1));

        correoEstudiante.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        panelDatosContacto.add(correoEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 145, 296, -1));

        correoEstudianteT.setBackground(new java.awt.Color(255, 255, 255));
        correoEstudianteT.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        correoEstudianteT.setForeground(new java.awt.Color(255, 255, 255));
        correoEstudianteT.setText("Correo:");
        panelDatosContacto.add(correoEstudianteT, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 126, -1, -1));

        telefonoEstudianteT.setBackground(new java.awt.Color(255, 255, 255));
        telefonoEstudianteT.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        telefonoEstudianteT.setForeground(new java.awt.Color(255, 255, 255));
        telefonoEstudianteT.setText("Teléfono:");
        panelDatosContacto.add(telefonoEstudianteT, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 182, -1, -1));

        celularEstudianteT.setBackground(new java.awt.Color(255, 255, 255));
        celularEstudianteT.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        celularEstudianteT.setForeground(new java.awt.Color(255, 255, 255));
        celularEstudianteT.setText("Celular:");
        panelDatosContacto.add(celularEstudianteT, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, -1, -1));

        telefonoEstudiante.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        panelDatosContacto.add(telefonoEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 201, 110, -1));

        celularEstudiante.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        panelDatosContacto.add(celularEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 130, -1));

        add(panelDatosContacto, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 50, 320, 230));

        guardar.setBackground(new java.awt.Color(101, 166, 148));
        guardar.setForeground(new java.awt.Color(255, 255, 255));
        guardar.setText("Guardar");
        guardar.setBorderPainted(false);
        guardar.setOpaque(true);
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });
        add(guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 540, -1, -1));

        panelInformacionEstudiante.setBackground(new java.awt.Color(102, 102, 102));
        panelInformacionEstudiante.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Informacion Del Estudiante", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 0, 13), new java.awt.Color(255, 255, 255))); // NOI18N
        panelInformacionEstudiante.setForeground(new java.awt.Color(255, 255, 255));
        panelInformacionEstudiante.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        primerNombreEstudianteT.setBackground(new java.awt.Color(255, 255, 255));
        primerNombreEstudianteT.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        primerNombreEstudianteT.setForeground(new java.awt.Color(255, 255, 255));
        primerNombreEstudianteT.setText("Primer Nombre:");
        panelInformacionEstudiante.add(primerNombreEstudianteT, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 78, -1, -1));

        primerNombreEstudiante.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        panelInformacionEstudiante.add(primerNombreEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 99, 216, -1));

        segundoNombreEstudianteT.setBackground(new java.awt.Color(255, 255, 255));
        segundoNombreEstudianteT.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        segundoNombreEstudianteT.setForeground(new java.awt.Color(255, 255, 255));
        segundoNombreEstudianteT.setText("Segundo Nombre:");
        panelInformacionEstudiante.add(segundoNombreEstudianteT, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 78, -1, -1));

        segundoNombreEstudiante.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        panelInformacionEstudiante.add(segundoNombreEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 99, 216, -1));

        primerApellidoEstudianteT.setBackground(new java.awt.Color(255, 255, 255));
        primerApellidoEstudianteT.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        primerApellidoEstudianteT.setForeground(new java.awt.Color(255, 255, 255));
        primerApellidoEstudianteT.setText("Primer Apellido:");
        panelInformacionEstudiante.add(primerApellidoEstudianteT, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 130, -1, -1));

        primerApellidoEstudiante.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        panelInformacionEstudiante.add(primerApellidoEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 151, 216, -1));

        segundoApellidoEstudianteT.setBackground(new java.awt.Color(255, 255, 255));
        segundoApellidoEstudianteT.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        segundoApellidoEstudianteT.setForeground(new java.awt.Color(255, 255, 255));
        segundoApellidoEstudianteT.setText("Segundo Apellido:");
        panelInformacionEstudiante.add(segundoApellidoEstudianteT, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 130, -1, -1));

        segundoApellidoEstudiante.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        panelInformacionEstudiante.add(segundoApellidoEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 151, 216, -1));

        sexoEstudianteT.setBackground(new java.awt.Color(255, 255, 255));
        sexoEstudianteT.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        sexoEstudianteT.setForeground(new java.awt.Color(255, 255, 255));
        sexoEstudianteT.setText("Sexo:");
        panelInformacionEstudiante.add(sexoEstudianteT, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, -1, -1));

        sexoEstudiante.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        sexoEstudiante.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione...", "Masculino", "Femenino" }));
        sexoEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sexoEstudianteActionPerformed(evt);
            }
        });
        panelInformacionEstudiante.add(sexoEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, -1, -1));

        rhEstudianteT.setBackground(new java.awt.Color(255, 255, 255));
        rhEstudianteT.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        rhEstudianteT.setForeground(new java.awt.Color(255, 255, 255));
        rhEstudianteT.setText("RH:");
        panelInformacionEstudiante.add(rhEstudianteT, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        rhEstudiante.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        rhEstudiante.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "...", "O-", "O+", "A-", "A+", "B-", "B+", "AB-", "AB+" }));
        panelInformacionEstudiante.add(rhEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        paisEstudianteT.setBackground(new java.awt.Color(255, 255, 255));
        paisEstudianteT.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        paisEstudianteT.setForeground(new java.awt.Color(255, 255, 255));
        paisEstudianteT.setText("Pais Nacimiento:");
        panelInformacionEstudiante.add(paisEstudianteT, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, -1, -1));

        paisEstudiante.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        paisEstudiante.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione..." }));
        paisEstudiante.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                paisEstudianteItemStateChanged(evt);
            }
        });
        panelInformacionEstudiante.add(paisEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, -1, -1));
        cargarPaises();

        fechaNacimientoT.setBackground(new java.awt.Color(255, 255, 255));
        fechaNacimientoT.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        fechaNacimientoT.setForeground(new java.awt.Color(255, 255, 255));
        fechaNacimientoT.setText("Fecha De Nacimiento:");
        panelInformacionEstudiante.add(fechaNacimientoT, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, -1, -1));

        estratoEstudianteT.setBackground(new java.awt.Color(255, 255, 255));
        estratoEstudianteT.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        estratoEstudianteT.setForeground(new java.awt.Color(255, 255, 255));
        estratoEstudianteT.setText("Estrato:");
        panelInformacionEstudiante.add(estratoEstudianteT, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        estratoEstudiante.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        estratoEstudiante.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { ".", "1", "2", "3", "4", "5", "6" }));
        panelInformacionEstudiante.add(estratoEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        fechaNacimiento.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        panelInformacionEstudiante.add(fechaNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, 170, -1));

        lugarNacimientoEstudianteT.setBackground(new java.awt.Color(255, 255, 255));
        lugarNacimientoEstudianteT.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        lugarNacimientoEstudianteT.setForeground(new java.awt.Color(255, 255, 255));
        lugarNacimientoEstudianteT.setText("Lugar Nacimiento:");
        panelInformacionEstudiante.add(lugarNacimientoEstudianteT, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, -1, -1));

        lugarNacimientoEstudiante.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        lugarNacimientoEstudiante.setText("Seleccione Un Pais");
        lugarNacimientoEstudiante.setEnabled(false);
        panelInformacionEstudiante.add(lugarNacimientoEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, 170, -1));

        idEstudiante.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        panelInformacionEstudiante.add(idEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 47, 216, -1));

        idEstudianteT.setBackground(new java.awt.Color(255, 255, 255));
        idEstudianteT.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        idEstudianteT.setForeground(new java.awt.Color(255, 255, 255));
        idEstudianteT.setText("Numero Identificación:");
        panelInformacionEstudiante.add(idEstudianteT, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 26, -1, -1));

        tipoDocumentoEstudianteT.setBackground(new java.awt.Color(255, 255, 255));
        tipoDocumentoEstudianteT.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        tipoDocumentoEstudianteT.setForeground(new java.awt.Color(255, 255, 255));
        tipoDocumentoEstudianteT.setText("Tipo:");
        panelInformacionEstudiante.add(tipoDocumentoEstudianteT, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 24, -1, -1));

        tipoDocumentoEstudiante.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        tipoDocumentoEstudiante.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione...", "Tarjeta Identidad", "Cedula Ciudadania", "Cedula Extranjeria", "Registro Civil", " " }));
        panelInformacionEstudiante.add(tipoDocumentoEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 45, -1, -1));

        add(panelInformacionEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 460, 290));

        panelDatosMedicos.setBackground(new java.awt.Color(102, 102, 102));
        panelDatosMedicos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos Medicos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 0, 13), new java.awt.Color(255, 255, 255))); // NOI18N
        panelDatosMedicos.setForeground(new java.awt.Color(255, 255, 255));
        panelDatosMedicos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nombreSaludEstudianteT.setBackground(new java.awt.Color(255, 255, 255));
        nombreSaludEstudianteT.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        nombreSaludEstudianteT.setForeground(new java.awt.Color(255, 255, 255));
        nombreSaludEstudianteT.setText("Nombre:");
        panelDatosMedicos.add(nombreSaludEstudianteT, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        nombreSaludEstudiante.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        nombreSaludEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreSaludEstudianteActionPerformed(evt);
            }
        });
        panelDatosMedicos.add(nombreSaludEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 296, -1));

        tipoSaludT.setBackground(new java.awt.Color(255, 255, 255));
        tipoSaludT.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        tipoSaludT.setForeground(new java.awt.Color(255, 255, 255));
        tipoSaludT.setText("Tipo:");
        panelDatosMedicos.add(tipoSaludT, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        tipoSalud.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        tipoSalud.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione...", "EPS", "SISBEN" }));
        tipoSalud.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                tipoSaludItemStateChanged(evt);
            }
        });
        tipoSalud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoSaludActionPerformed(evt);
            }
        });
        panelDatosMedicos.add(tipoSalud, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        nivelSisbenT.setBackground(new java.awt.Color(255, 255, 255));
        nivelSisbenT.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        nivelSisbenT.setForeground(new java.awt.Color(255, 255, 255));
        nivelSisbenT.setText("Nivel:");
        panelDatosMedicos.add(nivelSisbenT, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        nivelSisben.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        nivelSisben.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione...", "1", "2" }));
        nivelSisben.setEnabled(false);
        nivelSisben.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nivelSisbenActionPerformed(evt);
            }
        });
        panelDatosMedicos.add(nivelSisben, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        add(panelDatosMedicos, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 320, 320, 200));
    }// </editor-fold>//GEN-END:initComponents

    
    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
        // TODO add your handling code here:
        boolean validos=validarCamposPanel();
        if(validos){
            String idEstudianteTmp=idEstudiante.getText();
            String tipoDocumentoEstudianteTmp=(String)tipoDocumentoEstudiante.getSelectedItem();
            String primerNombreEstudianteTmp=primerNombreEstudiante.getText();
            String segundoNombreEstudianteTmp=segundoNombreEstudiante.getText();
            String primerApellidoEstudianteTmp=primerApellidoEstudiante.getText();
            String segundoApellidoEstudianteTmp=segundoApellidoEstudiante.getText();
            String rhEstudianteTmp=(String)rhEstudiante.getSelectedItem();
            String sexoEstudianteTmp=(String)sexoEstudiante.getSelectedItem();
            Date fechaNacimientoTmp=fechaNacimiento.getDate();
            String estratoEstudianteTmp=(String)estratoEstudiante.getSelectedItem();
            String paisEstudianteTmp=(String)paisEstudiante.getSelectedItem();
            String lugarNacimientoEstudianteTmp=(String)lugarNacimientoEstudiante.getText();
            String idFamiliarTmp=(String)idFamiliar.getText();
            String tipoDocumentoFamiliarTmp=(String)tipoDocumentoFamiliar.getSelectedItem();
            String primerNombreFamiliarTmp=(String)primerNombreFamiliar.getText();
            String segundoNombreFamiliarTmp=(String)segundoNombreFamiliar.getText();
            String primerApellidoFamiliarTmp=(String)primerApellidoFamiliar.getText();
            String segundoApellidoFamiliarTmp=(String)segundoApellidoFamiliar.getText();
            String profesionFamiliarTmp=(String)profesionFamiliar.getText();
            String parentescoFamiliarTmp=(String)parentescoFamiliar.getText();
            String direccionEstudianteTmp=(String)direccionEstudiante.getText();
            String barrioEstudianteTmp=(String)barrioEstudiante.getText();
            String correoEstudianteTmp=(String)correoEstudiante.getText();
            String telefonoEstudianteTmp=(String)telefonoEstudiante.getText();
            String celularEstudianteTmp=(String)celularEstudiante.getText();
            String tipoSaludTmp=(String)tipoSalud.getSelectedItem();
            String nombreSaludEstudianteTmp=(String)nombreSaludEstudiante.getText();
            String nivelSisbenTmp=(String)nivelSisben.getSelectedItem();
            controlAgregarEstudiantePanel.AgregarEstudiante(idEstudianteTmp,tipoDocumentoEstudianteTmp,
                    primerNombreEstudianteTmp,segundoNombreEstudianteTmp,primerApellidoEstudianteTmp,
                    segundoApellidoEstudianteTmp,rhEstudianteTmp,sexoEstudianteTmp,fechaNacimientoTmp,
                    estratoEstudianteTmp,paisEstudianteTmp,lugarNacimientoEstudianteTmp,idFamiliarTmp,
                    tipoDocumentoFamiliarTmp,primerNombreFamiliarTmp,segundoNombreFamiliarTmp,
                    primerApellidoFamiliarTmp,segundoApellidoFamiliarTmp,profesionFamiliarTmp,
                    parentescoFamiliarTmp,direccionEstudianteTmp,barrioEstudianteTmp,correoEstudianteTmp,
                    telefonoEstudianteTmp,celularEstudianteTmp,tipoSaludTmp,nombreSaludEstudianteTmp,
                    nivelSisbenTmp);
            JOptionPane mensaje= new JOptionPane();
            mensaje.setBackground(new java.awt.Color(102, 102, 102));
            mensaje.setForeground(Color.white);
            mensaje.showMessageDialog(null,"Se ha registrado un nuevo estudiante");
        }
        else{
           JOptionPane mensaje= new JOptionPane();
            mensaje.setBackground(new java.awt.Color(102, 102, 102));
            mensaje.setForeground(Color.white);
            mensaje.showMessageDialog(null,"Debes completar los campos indicados"); 
        }
        
    }//GEN-LAST:event_guardarActionPerformed

    private void direccionEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_direccionEstudianteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_direccionEstudianteActionPerformed

    private void sexoEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sexoEstudianteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sexoEstudianteActionPerformed

    private void nombreSaludEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreSaludEstudianteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreSaludEstudianteActionPerformed

    private void tipoSaludActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoSaludActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoSaludActionPerformed

    private void paisEstudianteItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_paisEstudianteItemStateChanged
        // TODO add your handling code here:
        if(evt.getStateChange()==ItemEvent.SELECTED){
            if(paisEstudiante.getSelectedIndex()>0){
                lugarNacimientoEstudiante.setEnabled(true);
                lugarNacimientoEstudiante.setText("");
            }
            else{
                lugarNacimientoEstudiante.setEnabled(false);
                lugarNacimientoEstudiante.setText("Seleccione un Pais");
            }
        }
    }//GEN-LAST:event_paisEstudianteItemStateChanged

    private void nivelSisbenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nivelSisbenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nivelSisbenActionPerformed

    private void tipoSaludItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_tipoSaludItemStateChanged
        // TODO add your handling code here:
        if(evt.getStateChange()==ItemEvent.SELECTED){
            if(tipoSalud.getSelectedIndex()==2){
                nivelSisben.setEnabled(true);
            }
            else{
                nivelSisben.setEnabled(false);
            }
        }
    }//GEN-LAST:event_tipoSaludItemStateChanged

    private final void cargarPaises(){
        String [] listadoPaises=controlAgregarEstudiantePanel.generarListadoPaises();
        listadoPaises[0]="Seleccione...";
        DefaultComboBoxModel paises= new DefaultComboBoxModel(listadoPaises);
        paisEstudiante.setModel(paises);
    }
    
    private boolean validarCamposPanel( ){
        boolean datosIncompletos=true;
      if(idEstudiante.getText().isEmpty()){
          idEstudianteT.setForeground(Color.red);
          datosIncompletos=false;
      }
      if(tipoDocumentoEstudiante.getSelectedIndex()==0){
         tipoDocumentoEstudianteT.setForeground(Color.red);
         datosIncompletos=false;
      }
      if(primerNombreEstudiante.getText().isEmpty()){
          primerNombreEstudianteT.setForeground(Color.red);
          datosIncompletos=false;
      }
      if(primerApellidoEstudiante.getText().isEmpty()){
          primerApellidoEstudianteT.setForeground(Color.red);
          datosIncompletos=false;
      }
      if(segundoApellidoEstudiante.getText().isEmpty()){
          segundoApellidoEstudianteT.setForeground(Color.red);
          datosIncompletos=false;
      }
      if(rhEstudiante.getSelectedIndex()==0){
          rhEstudianteT.setForeground(Color.red);
          datosIncompletos=false;
      }
      if(sexoEstudiante.getSelectedIndex()==0){
          sexoEstudianteT.setForeground(Color.red);
          datosIncompletos=false;
      }
      if(fechaNacimiento.getDate()==null){
          fechaNacimientoT.setForeground(Color.red);
          datosIncompletos=false;
      }
      if(estratoEstudiante.getSelectedIndex()==0){
          estratoEstudianteT.setForeground(Color.red);
          datosIncompletos=false;
      }
      if(paisEstudiante.getSelectedIndex()==0){
          paisEstudianteT.setForeground(Color.red);
          datosIncompletos=false;
      }
      if(lugarNacimientoEstudiante.getText().isEmpty()){
          lugarNacimientoEstudianteT.setForeground(Color.red);
          datosIncompletos=false;
      }
      if(idFamiliar.getText().isEmpty()){
          idFamiliarT.setForeground(Color.red);
          datosIncompletos=false;
      }
      if(tipoDocumentoFamiliar.getSelectedIndex()==0){
          tipoDocumentoFamiliarT.setForeground(Color.red);
          datosIncompletos=false;
      }
      if(tipoDocumentoFamiliar.getSelectedIndex()==0){
         tipoDocumentoFamiliarT.setForeground(Color.red);
         datosIncompletos=false;
      }
      if(primerNombreFamiliar.getText().isEmpty()){
          primerNombreFamiliarT.setForeground(Color.red);
          datosIncompletos=false;
      }
      if(primerApellidoFamiliar.getText().isEmpty()){
          primerApellidoFamiliarT.setForeground(Color.red);
          datosIncompletos=false;
      }
      if(segundoApellidoFamiliar.getText().isEmpty()){
          segundoApellidoFamiliarT.setForeground(Color.red);
          datosIncompletos=false;
      }
      if(profesionFamiliar.getText().isEmpty()){
          profesionFamiliarT.setForeground(Color.red);
          datosIncompletos=false;
      }
      if(parentescoFamiliar.getText().isEmpty()){
          parentescoFamiliarT.setForeground(Color.red);
          datosIncompletos=false;
      }
      if(direccionEstudiante.getText().isEmpty()){
          direccionEstudianteT.setForeground(Color.red);
          datosIncompletos=false;
      }
      if(barrioEstudiante.getText().isEmpty()){
          barrioEstudianteT.setForeground(Color.red);
          datosIncompletos=false;
      }
      if(correoEstudiante.getText().isEmpty()){
          correoEstudianteT.setForeground(Color.red);
          datosIncompletos=false;
      }
      if(telefonoEstudiante.getText().isEmpty()){
          telefonoEstudianteT.setForeground(Color.red);
          datosIncompletos=false;
      }
      if(celularEstudiante.getText().isEmpty()){
          celularEstudianteT.setForeground(Color.red);
          datosIncompletos=false;
      }
      if(nombreSaludEstudiante.getText().isEmpty()){
          nombreSaludEstudianteT.setForeground(Color.red);
          datosIncompletos=false;
      }
      if(tipoSalud.getSelectedIndex()==0){
         tipoSaludT.setForeground(Color.red);
         datosIncompletos=false;
      }
      if(tipoSalud.getSelectedIndex()==2 && nivelSisben.getSelectedIndex()==0){
         nivelSisbenT.setForeground(Color.red);
         datosIncompletos=false;
      }    
      return datosIncompletos;
    }
    
    
    
    private ControlAgregarEstudiantePanel controlAgregarEstudiantePanel;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField barrioEstudiante;
    private javax.swing.JLabel barrioEstudianteT;
    private javax.swing.JTextField celularEstudiante;
    private javax.swing.JLabel celularEstudianteT;
    private javax.swing.JTextField correoEstudiante;
    private javax.swing.JLabel correoEstudianteT;
    private javax.swing.JTextField direccionEstudiante;
    private javax.swing.JLabel direccionEstudianteT;
    private javax.swing.JComboBox<String> estratoEstudiante;
    private javax.swing.JLabel estratoEstudianteT;
    private com.toedter.calendar.JDateChooser fechaNacimiento;
    private javax.swing.JLabel fechaNacimientoT;
    private javax.swing.JButton guardar;
    private javax.swing.JTextField idEstudiante;
    private javax.swing.JLabel idEstudianteT;
    private javax.swing.JTextField idFamiliar;
    private javax.swing.JLabel idFamiliarT;
    private javax.swing.JTextField lugarNacimientoEstudiante;
    private javax.swing.JLabel lugarNacimientoEstudianteT;
    private javax.swing.JComboBox<String> nivelSisben;
    private javax.swing.JLabel nivelSisbenT;
    private javax.swing.JTextField nombreSaludEstudiante;
    private javax.swing.JLabel nombreSaludEstudianteT;
    private javax.swing.JComboBox<String> paisEstudiante;
    private javax.swing.JLabel paisEstudianteT;
    private javax.swing.JPanel panelDatosContacto;
    private javax.swing.JPanel panelDatosFamiliar;
    private javax.swing.JPanel panelDatosMedicos;
    private javax.swing.JPanel panelInformacionEstudiante;
    private javax.swing.JTextField parentescoFamiliar;
    private javax.swing.JLabel parentescoFamiliarT;
    private javax.swing.JTextField primerApellidoEstudiante;
    private javax.swing.JLabel primerApellidoEstudianteT;
    private javax.swing.JTextField primerApellidoFamiliar;
    private javax.swing.JLabel primerApellidoFamiliarT;
    private javax.swing.JTextField primerNombreEstudiante;
    private javax.swing.JLabel primerNombreEstudianteT;
    private javax.swing.JTextField primerNombreFamiliar;
    private javax.swing.JLabel primerNombreFamiliarT;
    private javax.swing.JTextField profesionFamiliar;
    private javax.swing.JLabel profesionFamiliarT;
    private javax.swing.JComboBox<String> rhEstudiante;
    private javax.swing.JLabel rhEstudianteT;
    private javax.swing.JTextField segundoApellidoEstudiante;
    private javax.swing.JLabel segundoApellidoEstudianteT;
    private javax.swing.JTextField segundoApellidoFamiliar;
    private javax.swing.JLabel segundoApellidoFamiliarT;
    private javax.swing.JTextField segundoNombreEstudiante;
    private javax.swing.JLabel segundoNombreEstudianteT;
    private javax.swing.JTextField segundoNombreFamiliar;
    private javax.swing.JLabel segundoNombreFamiliarT;
    private javax.swing.JComboBox<String> sexoEstudiante;
    private javax.swing.JLabel sexoEstudianteT;
    private javax.swing.JTextField telefonoEstudiante;
    private javax.swing.JLabel telefonoEstudianteT;
    private javax.swing.JComboBox<String> tipoDocumentoEstudiante;
    private javax.swing.JLabel tipoDocumentoEstudianteT;
    private javax.swing.JComboBox<String> tipoDocumentoFamiliar;
    private javax.swing.JLabel tipoDocumentoFamiliarT;
    private javax.swing.JComboBox<String> tipoSalud;
    private javax.swing.JLabel tipoSaludT;
    // End of variables declaration//GEN-END:variables
}
