/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import control.ControlAdministrarRecursos;
import java.awt.Color;
import javax.swing.JOptionPane;


/**
 *
 * @author ferchs
 */
public class AgregarJornadaPanel extends javax.swing.JPanel {

    /**
     * Creates new form AgregarEstudiantePanel
     */
    public AgregarJornadaPanel() {
        controlAdministrarSalones= new ControlAdministrarRecursos();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelInformacionJornada = new javax.swing.JPanel();
        nombreJornadaT = new javax.swing.JLabel();
        nombreJornada = new javax.swing.JTextField();
        horaInicioT = new javax.swing.JLabel();
        idJornada = new javax.swing.JTextField();
        idJornadaT = new javax.swing.JLabel();
        horaFinT = new javax.swing.JLabel();
        horaFin = new javax.swing.JComboBox<>();
        horaInicio = new javax.swing.JComboBox<>();
        guardar = new javax.swing.JButton();

        setBackground(new java.awt.Color(102, 102, 102));
        setForeground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelInformacionJornada.setBackground(new java.awt.Color(102, 102, 102));
        panelInformacionJornada.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Informacion de la jornada", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 0, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        panelInformacionJornada.setForeground(new java.awt.Color(255, 255, 255));
        panelInformacionJornada.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nombreJornadaT.setBackground(new java.awt.Color(255, 255, 255));
        nombreJornadaT.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        nombreJornadaT.setForeground(new java.awt.Color(255, 255, 255));
        nombreJornadaT.setText("Nombre:");
        panelInformacionJornada.add(nombreJornadaT, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        nombreJornada.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        panelInformacionJornada.add(nombreJornada, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 380, -1));

        horaInicioT.setBackground(new java.awt.Color(255, 255, 255));
        horaInicioT.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        horaInicioT.setForeground(new java.awt.Color(255, 255, 255));
        horaInicioT.setText("Hora Inicio:");
        panelInformacionJornada.add(horaInicioT, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        idJornada.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        idJornada.setForeground(new java.awt.Color(204, 204, 204));
        idJornada.setText("Debe ser un numero");
        idJornada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                idJornadaMouseClicked(evt);
            }
        });
        panelInformacionJornada.add(idJornada, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 380, -1));

        idJornadaT.setBackground(new java.awt.Color(255, 255, 255));
        idJornadaT.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        idJornadaT.setForeground(new java.awt.Color(255, 255, 255));
        idJornadaT.setText("Id Jornada:");
        panelInformacionJornada.add(idJornadaT, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        horaFinT.setBackground(new java.awt.Color(255, 255, 255));
        horaFinT.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        horaFinT.setForeground(new java.awt.Color(255, 255, 255));
        horaFinT.setText("Hora Fin:");
        panelInformacionJornada.add(horaFinT, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));

        horaFin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione...", "12:00 AM", "1:00 AM", "2:00 AM", "3:00 AM", "4:00 AM", "5:00 AM", "6:00 AM", "7:00 AM", "8:00 AM", "9:00 AM", "10:00 AM", "11:00 AM", "12:00 PM", "1:00 PM", "2:00 PM", "3:00 PM", "4:00 PM", "5:00 PM", "6:00 PM", "7:00 PM", "8:00 PM", "9:00 PM", "10:00 PM", "11:00 PM" }));
        panelInformacionJornada.add(horaFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, -1));

        horaInicio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione...", "12:00 AM", "1:00 AM", "2:00 AM", "3:00 AM", "4:00 AM", "5:00 AM", "6:00 AM", "7:00 AM", "8:00 AM", "9:00 AM", "10:00 AM", "11:00 AM", "12:00 PM", "1:00 PM", "2:00 PM", "3:00 PM", "4:00 PM", "5:00 PM", "6:00 PM", "7:00 PM", "8:00 PM", "9:00 PM", "10:00 PM", "11:00 PM" }));
        panelInformacionJornada.add(horaInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        add(panelInformacionJornada, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 410, 370));

        guardar.setBackground(new java.awt.Color(101, 166, 148));
        guardar.setForeground(new java.awt.Color(255, 255, 255));
        guardar.setText("Guardar");
        guardar.setBorderPainted(false);
        guardar.setOpaque(true);
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });
        add(guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 480, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
        // TODO add your handling code here:
        boolean validos=validarCamposPanel();
        if(validos){
            int idJornadaTmp=Integer.parseInt(idJornada.getText().trim());
            String nombreJornadaTmp=nombreJornada.getText().trim();
            String horaInicioTmp=(String)horaInicio.getSelectedItem();
            String horaFinTmp=(String)horaFin.getSelectedItem();
            controlAdministrarSalones.agregarJornada(idJornadaTmp, nombreJornadaTmp, horaInicioTmp, horaFinTmp);
            JOptionPane mensaje= new JOptionPane();
            mensaje.setBackground(new java.awt.Color(102, 102, 102));
            mensaje.setForeground(Color.white);
            mensaje.showMessageDialog(null,"Se ha registrado una nueva jornada");
            limpiarCampos();
        }
        else{
            JOptionPane mensaje= new JOptionPane();
            mensaje.setBackground(new java.awt.Color(102, 102, 102));
            mensaje.setForeground(Color.white);
            mensaje.showMessageDialog(null,"Debes completar los campos indicados");
        }
    }//GEN-LAST:event_guardarActionPerformed

    private void idJornadaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_idJornadaMouseClicked
        // TODO add your handling code here:
        idJornada.setForeground(Color.BLACK);
        idJornada.setText("");
    }//GEN-LAST:event_idJornadaMouseClicked

    private boolean validarCamposPanel( ){
        boolean datosCompletos=true;
      if(idJornada.getText().isEmpty()){
          try{
          idJornadaT.setForeground(Color.red);
          int idSalonTmp=Integer.parseInt(idJornada.getText().trim());
          }
          catch(Exception e){
            idJornada.setText("El Id debe ser un numero");
            datosCompletos=false;
          }
      }
      if(nombreJornada.getText().isEmpty()){
          nombreJornadaT.setForeground(Color.red);
          datosCompletos=false;
      }
      if(horaInicio.getSelectedIndex()==0){
          horaInicioT.setForeground(Color.red);
          datosCompletos=false;
      }
      if(horaFin.getSelectedIndex()==0){
          horaFinT.setForeground(Color.red);
          datosCompletos=false;
      }
      return datosCompletos;
    }
    
    private void limpiarCampos(){
        idJornada.setText("");
        idJornadaT.setForeground(Color.WHITE);
        nombreJornada.setText("");
        nombreJornadaT.setForeground(Color.WHITE);
        horaInicio.setSelectedIndex(0);
        horaInicioT.setForeground(Color.WHITE);
        horaFin.setSelectedIndex(0);
        horaFinT.setForeground(Color.WHITE);
    }
    
    private ControlAdministrarRecursos controlAdministrarSalones;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton guardar;
    private javax.swing.JComboBox<String> horaFin;
    private javax.swing.JLabel horaFinT;
    private javax.swing.JComboBox<String> horaInicio;
    private javax.swing.JLabel horaInicioT;
    private javax.swing.JTextField idJornada;
    private javax.swing.JLabel idJornadaT;
    private javax.swing.JTextField nombreJornada;
    private javax.swing.JLabel nombreJornadaT;
    private javax.swing.JPanel panelInformacionJornada;
    // End of variables declaration//GEN-END:variables
}
