/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import control.ControlAdministrarRecursos;
import java.awt.Color;
import javax.swing.JOptionPane;



/**
 *
 * @author ferchs
 */
public class AgregarMateriaPanel extends javax.swing.JPanel {

    /**
     * Creates new form AgregarEstudiantePanel
     */
    public AgregarMateriaPanel() {
      initComponents();
      controlAdministrarMaterias= new ControlAdministrarRecursos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelInformacionSalon = new javax.swing.JPanel();
        nombre = new javax.swing.JTextField();
        nombreT = new javax.swing.JLabel();
        codigo = new javax.swing.JTextField();
        codigoT = new javax.swing.JLabel();
        guardar = new javax.swing.JButton();

        setBackground(new java.awt.Color(102, 102, 102));
        setForeground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelInformacionSalon.setBackground(new java.awt.Color(102, 102, 102));
        panelInformacionSalon.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Informacion de la Asignatura", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 0, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        panelInformacionSalon.setForeground(new java.awt.Color(255, 255, 255));
        panelInformacionSalon.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nombre.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        panelInformacionSalon.add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 300, -1));

        nombreT.setBackground(new java.awt.Color(255, 255, 255));
        nombreT.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        nombreT.setForeground(new java.awt.Color(255, 255, 255));
        nombreT.setText("Nombre:");
        panelInformacionSalon.add(nombreT, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        codigo.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        codigo.setForeground(new java.awt.Color(204, 204, 204));
        codigo.setText("Ingresa un numero");
        codigo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                codigoMouseClicked(evt);
            }
        });
        panelInformacionSalon.add(codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 170, -1));

        codigoT.setBackground(new java.awt.Color(255, 255, 255));
        codigoT.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        codigoT.setForeground(new java.awt.Color(255, 255, 255));
        codigoT.setText("Codigo:");
        panelInformacionSalon.add(codigoT, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        add(panelInformacionSalon, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 410, 280));

        guardar.setBackground(new java.awt.Color(101, 166, 148));
        guardar.setForeground(new java.awt.Color(255, 255, 255));
        guardar.setText("Guardar");
        guardar.setBorderPainted(false);
        guardar.setOpaque(true);
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });
        add(guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 440, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
        // TODO add your handling code here:
        boolean validos=validarCamposPanel();
        if(validos){
            int codigoTmp=Integer.parseInt(codigo.getText().trim());
            String nombreTmp=nombre.getText().trim();
            controlAdministrarMaterias.agregarMateria(codigoTmp, nombreTmp);
            JOptionPane mensaje= new JOptionPane();
            mensaje.setBackground(new java.awt.Color(102, 102, 102));
            mensaje.setForeground(Color.white);
            mensaje.showMessageDialog(null,"Se ha registrado una nueva materia");
            limpiarCampos();
        }
        else{
            JOptionPane mensaje= new JOptionPane();
            mensaje.setBackground(new java.awt.Color(102, 102, 102));
            mensaje.setForeground(Color.white);
            mensaje.showMessageDialog(null,"Debes completar los campos indicados"); 
        }
    }//GEN-LAST:event_guardarActionPerformed

    private void codigoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_codigoMouseClicked
        // TODO add your handling code here:
        codigo.setText("");
        codigo.setForeground(Color.BLACK);
    }//GEN-LAST:event_codigoMouseClicked

    private boolean validarCamposPanel( ){
        boolean datosCompletos=true;
      if(codigo.getText().isEmpty()){
          try{
          codigoT.setForeground(Color.red);
          Integer.parseInt(nombre.getText().trim());
          }
          catch(Exception e){
            codigo.setText("Debe ser un numero");
            datosCompletos=false;
          }
      }
      if(nombre.getText().isEmpty()){
          nombreT.setForeground(Color.red);
          datosCompletos=false;
      }
      
      return datosCompletos;
    }
    
    private void limpiarCampos(){
        codigo.setText("");
        codigoT.setForeground(Color.WHITE);
        nombre.setText("");
        nombreT.setForeground(Color.WHITE);
    }
    
    private ControlAdministrarRecursos controlAdministrarMaterias;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField codigo;
    private javax.swing.JLabel codigoT;
    private javax.swing.JButton guardar;
    private javax.swing.JTextField nombre;
    private javax.swing.JLabel nombreT;
    private javax.swing.JPanel panelInformacionSalon;
    // End of variables declaration//GEN-END:variables
}
