/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.JPanel;

/**
 *
 * @author ferchs
 */
public class CursosPanel extends javax.swing.JPanel {

    private VentanaPrincipal ventanaPrincipal;
    private JPanel actual;
    /**
     * Creates new form Estudiantes
     */
    public CursosPanel(VentanaPrincipal principal) {
        initComponents();
        ventanaPrincipal=principal;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelLogo1 = new javax.swing.JPanel();
        administrarCursos = new javax.swing.JButton();
        agregarText = new javax.swing.JLabel();
        inicio = new javax.swing.JButton();
        inicioText = new javax.swing.JLabel();
        gestionarEvaluaciones = new javax.swing.JButton();
        buscarText1 = new javax.swing.JLabel();
        administrarExamenes1 = new javax.swing.JButton();
        buscarText3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(102, 102, 102));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelLogo1.setBackground(new java.awt.Color(101, 166, 148));
        PanelLogo1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        administrarCursos.setBackground(new java.awt.Color(102, 102, 102));
        administrarCursos.setForeground(new java.awt.Color(255, 255, 255));
        administrarCursos.setIcon(new javax.swing.ImageIcon("/Users/ferchs/Desktop/cursosMini.png")); // NOI18N
        administrarCursos.setBorderPainted(false);
        administrarCursos.setOpaque(true);
        administrarCursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                administrarCursosActionPerformed(evt);
            }
        });
        PanelLogo1.add(administrarCursos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 70, -1));

        agregarText.setBackground(new java.awt.Color(255, 255, 255));
        agregarText.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        agregarText.setForeground(new java.awt.Color(255, 255, 255));
        agregarText.setText("<html>\n<pre>Administrar\n  Cursos\n</pre>\n</html>");
        PanelLogo1.add(agregarText, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, -1, -1));

        inicio.setBackground(new java.awt.Color(102, 102, 102));
        inicio.setForeground(new java.awt.Color(255, 255, 255));
        inicio.setIcon(new javax.swing.ImageIcon("/Users/ferchs/Desktop/inicio.png")); // NOI18N
        inicio.setBorderPainted(false);
        inicio.setOpaque(true);
        inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inicioActionPerformed(evt);
            }
        });
        PanelLogo1.add(inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 510, 70, -1));

        inicioText.setBackground(new java.awt.Color(255, 255, 255));
        inicioText.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        inicioText.setForeground(new java.awt.Color(255, 255, 255));
        inicioText.setText("inicio");
        PanelLogo1.add(inicioText, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 560, -1, -1));

        gestionarEvaluaciones.setBackground(new java.awt.Color(102, 102, 102));
        gestionarEvaluaciones.setForeground(new java.awt.Color(255, 255, 255));
        gestionarEvaluaciones.setIcon(new javax.swing.ImageIcon("/Users/ferchs/Desktop/evaluacionMini.png")); // NOI18N
        gestionarEvaluaciones.setBorderPainted(false);
        gestionarEvaluaciones.setOpaque(true);
        gestionarEvaluaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestionarEvaluacionesActionPerformed(evt);
            }
        });
        PanelLogo1.add(gestionarEvaluaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 70, -1));

        buscarText1.setBackground(new java.awt.Color(255, 255, 255));
        buscarText1.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        buscarText1.setForeground(new java.awt.Color(255, 255, 255));
        buscarText1.setText("<html>\n<pre>  Gestionar\nEvaluaciones</pre>\n</html>");
        PanelLogo1.add(buscarText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, -1, -1));

        administrarExamenes1.setBackground(new java.awt.Color(102, 102, 102));
        administrarExamenes1.setForeground(new java.awt.Color(255, 255, 255));
        administrarExamenes1.setIcon(new javax.swing.ImageIcon("/Users/ferchs/Desktop/examenMin.png")); // NOI18N
        administrarExamenes1.setBorderPainted(false);
        administrarExamenes1.setOpaque(true);
        administrarExamenes1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                administrarExamenes1ActionPerformed(evt);
            }
        });
        PanelLogo1.add(administrarExamenes1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 70, -1));

        buscarText3.setBackground(new java.awt.Color(255, 255, 255));
        buscarText3.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        buscarText3.setForeground(new java.awt.Color(255, 255, 255));
        buscarText3.setText("<html> \n<pre> Gestionar  \n   Notas</pre> \n</html>");
        PanelLogo1.add(buscarText3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, -1, -1));

        add(PanelLogo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 580));
    }// </editor-fold>//GEN-END:initComponents

    private void administrarCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_administrarCursosActionPerformed
        // TODO add your handling code here:
        AdministrarCursosPanel administrarCursosPanel= new AdministrarCursosPanel(this);
        ventanaPrincipal.mostarPanel(administrarCursosPanel);
    }//GEN-LAST:event_administrarCursosActionPerformed

    private void inicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inicioActionPerformed
        // TODO add your handling code here:
        ventanaPrincipal.mostarMenu();
    }//GEN-LAST:event_inicioActionPerformed

    private void gestionarEvaluacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestionarEvaluacionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gestionarEvaluacionesActionPerformed

    private void administrarExamenes1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_administrarExamenes1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_administrarExamenes1ActionPerformed

    public void mostarPanel(JPanel panel){
        if(actual!=null){
            remove(actual);
        }
        actual=panel;
        add(panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 810, 580));
        revalidate();
        repaint();
    }
    
    public void mostrarInicio(){
        ventanaPrincipal.mostarMenu();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelLogo1;
    private javax.swing.JButton administrarCursos;
    private javax.swing.JButton administrarExamenes1;
    private javax.swing.JLabel agregarText;
    private javax.swing.JLabel buscarText1;
    private javax.swing.JLabel buscarText3;
    private javax.swing.JButton gestionarEvaluaciones;
    private javax.swing.JButton inicio;
    private javax.swing.JLabel inicioText;
    // End of variables declaration//GEN-END:variables
}
