/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import control.ControlAdministrarCursos;
import java.awt.Color;
import java.text.ParseException;
import java.util.HashMap;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;



/**
 *
 * @author ferchs
 */
public class EditarCursoPanel extends javax.swing.JPanel {

    /**
     * Creates new form AgregarEstudiantePanel
     */
    public EditarCursoPanel() {
      controlAdministrarCursos= new ControlAdministrarCursos();
      initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelInformacionCurso = new javax.swing.JPanel();
        salonT = new javax.swing.JLabel();
        gradoT = new javax.swing.JLabel();
        consecutivo = new javax.swing.JComboBox<>();
        consecutivoT = new javax.swing.JLabel();
        salon = new javax.swing.JComboBox<>();
        grado = new javax.swing.JComboBox<>();
        jornadaT = new javax.swing.JLabel();
        jornada = new javax.swing.JComboBox<>();
        directorT = new javax.swing.JLabel();
        director = new javax.swing.JComboBox<>();
        guardar = new javax.swing.JButton();

        setBackground(new java.awt.Color(102, 102, 102));
        setForeground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelInformacionCurso.setBackground(new java.awt.Color(102, 102, 102));
        panelInformacionCurso.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Informacion del curso", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 0, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        panelInformacionCurso.setForeground(new java.awt.Color(255, 255, 255));
        panelInformacionCurso.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        salonT.setBackground(new java.awt.Color(255, 255, 255));
        salonT.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        salonT.setForeground(new java.awt.Color(255, 255, 255));
        salonT.setText("Salon:");
        panelInformacionCurso.add(salonT, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        gradoT.setBackground(new java.awt.Color(255, 255, 255));
        gradoT.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        gradoT.setForeground(new java.awt.Color(255, 255, 255));
        gradoT.setText("Grado:");
        panelInformacionCurso.add(gradoT, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        consecutivo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione...", "1", "2", "3", "4", "5" }));
        consecutivo.setEnabled(false);
        panelInformacionCurso.add(consecutivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, -1, -1));

        consecutivoT.setBackground(new java.awt.Color(255, 255, 255));
        consecutivoT.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        consecutivoT.setForeground(new java.awt.Color(255, 255, 255));
        consecutivoT.setText("Consecutivo:");
        panelInformacionCurso.add(consecutivoT, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, -1, -1));

        salon.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione..." }));
        cargarSalones();
        panelInformacionCurso.add(salon, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        grado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione...", "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        grado.setEnabled(false);
        cargarGrados();
        panelInformacionCurso.add(grado, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jornadaT.setBackground(new java.awt.Color(255, 255, 255));
        jornadaT.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jornadaT.setForeground(new java.awt.Color(255, 255, 255));
        jornadaT.setText("Jornada:");
        panelInformacionCurso.add(jornadaT, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, -1, -1));

        jornada.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione..." }));
        cargarJornadas();
        panelInformacionCurso.add(jornada, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, -1, -1));

        directorT.setBackground(new java.awt.Color(255, 255, 255));
        directorT.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        directorT.setForeground(new java.awt.Color(255, 255, 255));
        directorT.setText("Director:");
        panelInformacionCurso.add(directorT, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, -1, -1));

        director.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione..." }));
        cargarProfesores();
        panelInformacionCurso.add(director, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, -1, -1));

        add(panelInformacionCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 370, 300));

        guardar.setBackground(new java.awt.Color(101, 166, 148));
        guardar.setForeground(new java.awt.Color(255, 255, 255));
        guardar.setText("Guardar");
        guardar.setBorderPainted(false);
        guardar.setOpaque(true);
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });
        add(guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 400, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
        // TODO add your handling code here:
        boolean validos=validarCamposPanel();
        if(validos){
            String gradoStr=(String) grado.getSelectedItem();
            String consecutivoStr=(String) consecutivo.getSelectedItem();
            int consecutivoTmp=Integer.parseInt(consecutivoStr);
            String salonTmp=(String)salon.getSelectedItem();
            int idSalon=controlAdministrarCursos.buscarIdSalon(salonTmp);
            String jornadaTmp=(String)jornada.getSelectedItem();
            int idJornada=controlAdministrarCursos.buscarIdJornada(jornadaTmp);
            String nombreDirectorTmp=(String)director.getSelectedItem();
            controlAdministrarCursos.editarCurso(gradoStr, consecutivoTmp, idSalon, idJornada,nombreDirectorTmp);
            JOptionPane mensaje= new JOptionPane();
            mensaje.setBackground(new java.awt.Color(102, 102, 102));
            mensaje.setForeground(Color.white);
            mensaje.showMessageDialog(null,"Se ha modificado exitosamente");
            limpiarCampos();
        }
        else{
            JOptionPane mensaje= new JOptionPane();
            mensaje.setBackground(new java.awt.Color(102, 102, 102));
            mensaje.setForeground(Color.white);
            mensaje.showMessageDialog(null,"Debes completar los campos indicados");
        }
    }//GEN-LAST:event_guardarActionPerformed

    private boolean validarCamposPanel( ){
        boolean datosCompletos=true;
      if(grado.getSelectedIndex()==0){
          gradoT.setForeground(Color.red);
          datosCompletos=false;
      }
      if(consecutivo.getSelectedIndex()==0){
          consecutivoT.setForeground(Color.red);
          datosCompletos=false;
      }
      if(jornada.getSelectedIndex()==0){
          jornadaT.setForeground(Color.red);
          datosCompletos=false;
      }
      if(salon.getSelectedIndex()==0){
          salonT.setForeground(Color.red);
          datosCompletos=false;
      }
      if(director.getSelectedIndex()==0){
          directorT.setForeground(Color.red);
          datosCompletos=false;
      }
      return datosCompletos;
    }
    
    private void limpiarCampos(){
        grado.setSelectedIndex(0);
        gradoT.setForeground(Color.WHITE);
        consecutivo.setSelectedIndex(0);
        consecutivoT.setForeground(Color.WHITE);
        salon.setSelectedIndex(0);
        salonT.setForeground(Color.WHITE);
        jornada.setSelectedIndex(0);
        jornadaT.setForeground(Color.WHITE);
        director.setSelectedIndex(0);
        directorT.setForeground(Color.WHITE);
    }
    
    
    private final void cargarGrados(){
        String [] listadoGrados=controlAdministrarCursos.obtenerListadoGrados();
        if(listadoGrados!=null){
        listadoGrados[0]="Seleccione...";
        DefaultComboBoxModel grados= new DefaultComboBoxModel(listadoGrados);
        grado.setModel(grados);
        }
        else{
            listadoGrados=new String[1];
            listadoGrados[0]="Seleccione...";
            DefaultComboBoxModel grados= new DefaultComboBoxModel(listadoGrados);
            grado.setModel(grados);
        }
    }
    
    private final void cargarSalones(){
        String [] listadoSalones=controlAdministrarCursos.obtenerListadoSalones();
        if(listadoSalones!=null){
        listadoSalones[0]="Seleccione...";
        DefaultComboBoxModel salones= new DefaultComboBoxModel(listadoSalones);
        salon.setModel(salones);
        }
        else{
            listadoSalones=new String[1];
            listadoSalones[0]="Seleccione...";
            DefaultComboBoxModel salones= new DefaultComboBoxModel(listadoSalones);
            grado.setModel(salones);
        }
    }
    
    private final void cargarJornadas(){
        String [] listadoJornadas=controlAdministrarCursos.obtenerListadoJornadas();
        if(listadoJornadas!=null){
        listadoJornadas[0]="Seleccione...";
        DefaultComboBoxModel jornadas= new DefaultComboBoxModel(listadoJornadas);
        jornada.setModel(jornadas);
        }
        else{
            listadoJornadas=new String[1];
            listadoJornadas[0]="Seleccione...";
            DefaultComboBoxModel jornadas= new DefaultComboBoxModel(listadoJornadas);
            grado.setModel(jornadas);
        }
    }
    
    private final void cargarProfesores(){
        String [] listadoProfesores=controlAdministrarCursos.obtenerListadoProfesores();
        if(listadoProfesores!=null){
        listadoProfesores[0]="Seleccione...";
        DefaultComboBoxModel profes= new DefaultComboBoxModel(listadoProfesores);
        director.setModel(profes);
        }
        else{
            listadoProfesores=new String[1];
            listadoProfesores[0]="Seleccione...";
            DefaultComboBoxModel profes= new DefaultComboBoxModel(listadoProfesores);
            grado.setModel(profes);
        }
    }
    
    public void llenarCampos(HashMap<String, String> campos) throws ParseException{
        MostrarItem(grado,campos.get("grado"));
        MostrarItem(consecutivo,campos.get("consecutivo"));
        MostrarItem(salon,campos.get("salon"));
        MostrarItem(jornada,campos.get("jornada"));
        MostrarItem(director,campos.get("director"));
    }
    
    private void MostrarItem(JComboBox comboBox, String itemSeleccionado){
         int num = comboBox.getItemCount();
         for (int i = 0; i < num; i++) {
            String item = (String) comboBox.getItemAt(i);
            if(itemSeleccionado.equals(item)){
                comboBox.setSelectedIndex(i);
            }
         }
    }
         
    private ControlAdministrarCursos controlAdministrarCursos;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> consecutivo;
    private javax.swing.JLabel consecutivoT;
    private javax.swing.JComboBox<String> director;
    private javax.swing.JLabel directorT;
    private javax.swing.JComboBox<String> grado;
    private javax.swing.JLabel gradoT;
    private javax.swing.JButton guardar;
    private javax.swing.JComboBox<String> jornada;
    private javax.swing.JLabel jornadaT;
    private javax.swing.JPanel panelInformacionCurso;
    private javax.swing.JComboBox<String> salon;
    private javax.swing.JLabel salonT;
    // End of variables declaration//GEN-END:variables
}
