/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import control.ControlAdministrarCursos;
import java.awt.Color;
import java.awt.event.ItemEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.InputStream;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import modelo.Boletin;
import modelo.Boletines;
import modelo.Grado;
import modelo.Institucion;
import modelo.ItemBoletin;
import modelo.ParametrosBoletin;
import modelo.entidades.Grados;
import modelo.entidades.Instituciones;
import net.sf.jasperreports.engine.JREmptyDataSource;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author ferchs
 */
public class GenerarBoletinesPanel extends javax.swing.JPanel  {

    /**
     * Creates new form AgregarEstudiantePanel
     */
    
    protected ReportesPanel reportesPanel;
    
    public GenerarBoletinesPanel(ReportesPanel reportesPanel) {
        controlAdministrarCursos= new ControlAdministrarCursos();
        initComponents();
        jScrollPane1= new JScrollPane();
        this.reportesPanel=reportesPanel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grado = new javax.swing.JComboBox<>();
        consecutivoT = new javax.swing.JLabel();
        consecutivo = new javax.swing.JComboBox<>();
        generar = new javax.swing.JButton();
        gradoT2 = new javax.swing.JLabel();
        rutaFisicaT = new javax.swing.JLabel();
        jFileChooser = new javax.swing.JFileChooser();
        gradoYcurso = new javax.swing.JLabel();

        setBackground(new java.awt.Color(102, 102, 102));
        setForeground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        grado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione...", "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        grado.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                gradoItemStateChanged(evt);
            }
        });
        cargarGrados();
        add(grado, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, -1, -1));

        consecutivoT.setBackground(new java.awt.Color(255, 255, 255));
        consecutivoT.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        consecutivoT.setForeground(new java.awt.Color(255, 255, 255));
        consecutivoT.setText("Consecutivo:");
        add(consecutivoT, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 50, -1, -1));

        consecutivo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione..." }));
        consecutivo.setEnabled(false);
        add(consecutivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 70, -1, -1));

        generar.setBackground(new java.awt.Color(101, 166, 148));
        generar.setForeground(new java.awt.Color(255, 255, 255));
        generar.setText("Generar");
        generar.setBorderPainted(false);
        generar.setOpaque(true);
        generar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generarActionPerformed(evt);
            }
        });
        add(generar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 510, 110, 30));

        gradoT2.setBackground(new java.awt.Color(255, 255, 255));
        gradoT2.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        gradoT2.setForeground(new java.awt.Color(255, 255, 255));
        gradoT2.setText("Grado:");
        add(gradoT2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, -1, -1));

        rutaFisicaT.setBackground(new java.awt.Color(255, 255, 255));
        rutaFisicaT.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        rutaFisicaT.setForeground(new java.awt.Color(255, 255, 255));
        rutaFisicaT.setText("Seleccione la ruta fisica donde se desea guardar los boletines:");
        add(rutaFisicaT, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 430, 20));

        jFileChooser.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);
        add(jFileChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 540, 350));

        gradoYcurso.setBackground(new java.awt.Color(255, 255, 255));
        gradoYcurso.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        gradoYcurso.setForeground(new java.awt.Color(255, 255, 255));
        gradoYcurso.setText("Seleccione el grado y curso del cual se desea generar los boletines");
        add(gradoYcurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 460, 20));
    }// </editor-fold>//GEN-END:initComponents

    private void generarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generarActionPerformed
        // TODO add your handling code here:  
        if(verificarCampos()){
            try {
                Institucion tmp= new Institucion();
                List<Instituciones> instituciones=tmp.findAll();
                Instituciones inst=instituciones.get(0);
                Boletines boletines= new Boletines();
                Grado grad= new Grado();
                String nombreGrado=(String) grado.getSelectedItem();
                Grados grados=grad.buscarGradoPorNombre(nombreGrado);
                int idGrado=grados.getGradosPK().getIdGrado();
                String consecutivoStr= (String) consecutivo.getSelectedItem();
                int idConsecutivo=Integer.parseInt(consecutivoStr);
                List listaParametros= new ArrayList<ParametrosBoletin>();
                ArrayList<Boletin> listaBoletines=boletines.obtenerInformacionBoletines(idGrado, idConsecutivo);
                for(int i=0;i<listaBoletines.size();i++){
                    Boletin boletin=listaBoletines.get(i);
                    ArrayList<ItemBoletin> items=boletin.obtenerItems();
                    for(int j=0;j<items.size();j++){
                        ItemBoletin it=items.get(j);
                        ParametrosBoletin parametros= new ParametrosBoletin(it.getNombreMateria(),it.getProfesor(),
                                it.getDefinitiva(),it.getDesempeño());
                        listaParametros.add(parametros);
                    }               
                JRBeanCollectionDataSource parametros= new JRBeanCollectionDataSource(listaParametros);
                Map datosBoletin = new HashMap();
                datosBoletin.put("NombreEstudiante", boletin.obtenerNombreEstudiante());
                datosBoletin.put("NombreInstitucion",inst.getNombre());
                datosBoletin.put("Nit",Integer.toString(inst.getNit()));
                datosBoletin.put("Direccion",inst.getDireccion());
                datosBoletin.put("Telefono",inst.getTelefono());
                datosBoletin.put("Correo",inst.getCorreo());
                JasperReport report =(JasperReport) JRLoader.loadObject("/Users/ferchs/NetBeansProjects/PruebaReporte/src/pruebareporte/Boletin.jasper");
//                JasperReport report =(JasperReport)JasperCompileManager.compileReport("/Users/ferchs/JaspersoftWorkspace/MyReports/Boletin.jrxml");
                JasperPrint print = JasperFillManager.fillReport(report, datosBoletin,parametros);
//                InputStream is=new FileInputStream("/Users/ferchs/JaspersoftWorkspace/MyReports/Boletin.jasper");
//                JasperReport report=(JasperReport) JRLoader.loadObject(is);
                File fichero=jFileChooser.getSelectedFile();
                String ruta=fichero.getAbsolutePath();
                JasperExportManager.exportReportToPdfFile(print,ruta+"/"+boletin.obtenerNombreEstudiante()+".pdf");
                JOptionPane mensaje= new JOptionPane();
            mensaje.setBackground(new java.awt.Color(102, 102, 102));
            mensaje.setForeground(Color.white);
            mensaje.showMessageDialog(null,"Se generaron los boletines del curso indicado");
                }
            } catch (JRException ex) {
                Logger.getLogger(GenerarBoletinesPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    }//GEN-LAST:event_generarActionPerformed

    private void gradoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_gradoItemStateChanged
        // TODO add your handling code here:
        if(evt.getStateChange()==ItemEvent.SELECTED){
            if(grado.getSelectedIndex()>0){
                String nombreGrado=(String) grado.getSelectedItem();
                String [] listadoConsecutivos=controlAdministrarCursos.obtenerListadoConsecutivosDeGrado(nombreGrado);
                if(listadoConsecutivos!=null){
                    listadoConsecutivos[0]="Seleccione...";
                    DefaultComboBoxModel grados= new DefaultComboBoxModel(listadoConsecutivos);
                    consecutivo.setModel(grados);
                    consecutivo.setEnabled(true);  
                }
                else{
                    JOptionPane mensaje= new JOptionPane();
                    mensaje.setBackground(new java.awt.Color(102, 102, 102));
                    mensaje.setForeground(Color.white);
                    mensaje.showMessageDialog(null,"No existen cursos creados para el grado "+nombreGrado);
                }
            }
            else{
                    consecutivo.setEnabled(false);
                    consecutivo.setSelectedIndex(0);
                }
        }
    }//GEN-LAST:event_gradoItemStateChanged

    private final void cargarGrados(){
        String [] listadoGrados=controlAdministrarCursos.obtenerListadoGrados();
        if(listadoGrados!=null){
        listadoGrados[0]="Seleccione...";
        DefaultComboBoxModel grados= new DefaultComboBoxModel(listadoGrados);
        grado.setModel(grados);
        }
        else{
            listadoGrados=new String[1];
            listadoGrados[0]="Seleccione...";
            DefaultComboBoxModel grados= new DefaultComboBoxModel(listadoGrados);
            grado.setModel(grados);
        }
    }
    
    private boolean verificarCampos(){
        if(grado.getSelectedIndex()==0){
            gradoYcurso.setForeground(Color.red);
            return false;
        }
        else{
            gradoYcurso.setForeground(Color.white);
        }
        if(consecutivo.getSelectedIndex()==0){
            gradoYcurso.setForeground(Color.red);
            return false;
        }
        else{
            gradoYcurso.setForeground(Color.white);
        }
        if(jFileChooser.getSelectedFile()==null){
            rutaFisicaT.setForeground(Color.red);
            return false;
        }
        else{
            rutaFisicaT.setForeground(Color.white);
        }
        return true;
    }
    
    private ControlAdministrarCursos controlAdministrarCursos;
    private JScrollPane jScrollPane1;
    private JTable ultimoResultadoBusqueda;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> consecutivo;
    private javax.swing.JLabel consecutivoT;
    private javax.swing.JButton generar;
    private javax.swing.JComboBox<String> grado;
    private javax.swing.JLabel gradoT2;
    private javax.swing.JLabel gradoYcurso;
    private javax.swing.JFileChooser jFileChooser;
    private javax.swing.JLabel rutaFisicaT;
    // End of variables declaration//GEN-END:variables
}
