/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.JPanel;

/**
 *
 * @author ferchs
 */
public class GestionarNotasPanel extends javax.swing.JPanel {

    private CursosPanel cursosPanel;
    private JPanel actual;
    
    /**
     * Creates new form AdministrarSalones
     */
    public GestionarNotasPanel(CursosPanel cursosPanel) {
        initComponents();
        this.cursosPanel=cursosPanel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelLogo1 = new javax.swing.JPanel();
        agregarExamen = new javax.swing.JButton();
        agregarExamenText = new javax.swing.JLabel();
        inicio = new javax.swing.JButton();
        inicioText = new javax.swing.JLabel();
        editar = new javax.swing.JButton();
        buscarText = new javax.swing.JLabel();

        setBackground(new java.awt.Color(102, 102, 102));
        setForeground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelLogo1.setBackground(new java.awt.Color(101, 166, 148));
        PanelLogo1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        agregarExamen.setBackground(new java.awt.Color(102, 102, 102));
        agregarExamen.setForeground(new java.awt.Color(255, 255, 255));
        agregarExamen.setIcon(new javax.swing.ImageIcon("/Users/ferchs/Desktop/MasMini.png")); // NOI18N
        agregarExamen.setBorderPainted(false);
        agregarExamen.setOpaque(true);
        agregarExamen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarExamenActionPerformed(evt);
            }
        });
        PanelLogo1.add(agregarExamen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 60, -1));

        agregarExamenText.setBackground(new java.awt.Color(255, 255, 255));
        agregarExamenText.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        agregarExamenText.setForeground(new java.awt.Color(255, 255, 255));
        agregarExamenText.setText("<html>\n<pre>Agregar\nExamen</pre>\n</html>");
        PanelLogo1.add(agregarExamenText, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        inicio.setBackground(new java.awt.Color(102, 102, 102));
        inicio.setForeground(new java.awt.Color(255, 255, 255));
        inicio.setIcon(new javax.swing.ImageIcon("/Users/ferchs/Desktop/inicio.png")); // NOI18N
        inicio.setBorderPainted(false);
        inicio.setOpaque(true);
        inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inicioActionPerformed(evt);
            }
        });
        PanelLogo1.add(inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 510, 60, -1));

        inicioText.setBackground(new java.awt.Color(255, 255, 255));
        inicioText.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        inicioText.setForeground(new java.awt.Color(255, 255, 255));
        inicioText.setText("inicio");
        PanelLogo1.add(inicioText, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 560, -1, -1));

        editar.setBackground(new java.awt.Color(102, 102, 102));
        editar.setForeground(new java.awt.Color(255, 255, 255));
        editar.setIcon(new javax.swing.ImageIcon("/Users/ferchs/Desktop/buscar.png")); // NOI18N
        editar.setBorderPainted(false);
        editar.setOpaque(true);
        editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarActionPerformed(evt);
            }
        });
        PanelLogo1.add(editar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 60, -1));

        buscarText.setBackground(new java.awt.Color(255, 255, 255));
        buscarText.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        buscarText.setForeground(new java.awt.Color(255, 255, 255));
        buscarText.setText("Buscar");
        PanelLogo1.add(buscarText, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        add(PanelLogo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, 580));
    }// </editor-fold>//GEN-END:initComponents

    private void agregarExamenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarExamenActionPerformed
        // TODO add your handling code here:
        AgregarExamenPanel agregarExamenPanel=new AgregarExamenPanel();
        mostarPanel(agregarExamenPanel);
    }//GEN-LAST:event_agregarExamenActionPerformed

    private void inicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inicioActionPerformed
        // TODO add your handling code here:
        cursosPanel.mostrarInicio();
    }//GEN-LAST:event_inicioActionPerformed

    private void editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarActionPerformed
        // TODO add your handling code here:
        BuscarExamenPanel buscarExamenPanel=new BuscarExamenPanel(this);
        mostarPanel(buscarExamenPanel);
    }//GEN-LAST:event_editarActionPerformed

    public void mostarPanel(JPanel panel){
        if(actual!=null){
            remove(actual);
        }
        actual=panel;
        add(panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 810, 580));
        revalidate();
        repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelLogo1;
    private javax.swing.JButton agregarExamen;
    private javax.swing.JLabel agregarExamenText;
    private javax.swing.JLabel buscarText;
    private javax.swing.JButton editar;
    private javax.swing.JButton inicio;
    private javax.swing.JLabel inicioText;
    // End of variables declaration//GEN-END:variables
}
