/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import control.ControlPrincipal;
import control.IniciarSesionControl;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author ferchs
 */
public class InicioSesion extends javax.swing.JFrame {

    /**
     * Creates new form InicioSesion
     */
    public InicioSesion() {
        initComponents();
        inicioSesionControl= new IniciarSesionControl();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        usuarioT = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        contraseñaT = new javax.swing.JLabel();
        contraseña = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        ingresar = new javax.swing.JButton();
        olvideCredenciales = new javax.swing.JButton();
        usuario = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 102));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(101, 166, 148));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon("/Users/ferchs/Downloads/login_icon.png")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon("/Users/ferchs/Creative Cloud Files/WebSoft2.png")); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 480));

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("INICIO DE SESION");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, -1, -1));

        usuarioT.setBackground(new java.awt.Color(255, 255, 255));
        usuarioT.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        usuarioT.setForeground(new java.awt.Color(255, 255, 255));
        usuarioT.setText("USUARIO");
        jPanel2.add(usuarioT, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, -1, -1));

        jSeparator2.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 240, -1));

        contraseñaT.setBackground(new java.awt.Color(255, 255, 255));
        contraseñaT.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        contraseñaT.setForeground(new java.awt.Color(255, 255, 255));
        contraseñaT.setText("CONTRASEÑA");
        jPanel2.add(contraseñaT, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, -1, -1));

        contraseña.setBackground(new java.awt.Color(102, 102, 102));
        contraseña.setForeground(new java.awt.Color(255, 255, 255));
        contraseña.setBorder(null);
        contraseña.setCaretColor(new java.awt.Color(255, 255, 255));
        jPanel2.add(contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 240, 20));

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 240, -1));

        ingresar.setBackground(new java.awt.Color(101, 166, 148));
        ingresar.setForeground(new java.awt.Color(255, 255, 255));
        ingresar.setText("Ingresar");
        ingresar.setBorderPainted(false);
        ingresar.setOpaque(true);
        ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresarActionPerformed(evt);
            }
        });
        jPanel2.add(ingresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, 130, 40));

        olvideCredenciales.setBackground(new java.awt.Color(102, 102, 102));
        olvideCredenciales.setForeground(new java.awt.Color(255, 255, 255));
        olvideCredenciales.setText("Olvide mis credenciales");
        olvideCredenciales.setBorderPainted(false);
        olvideCredenciales.setOpaque(true);
        olvideCredenciales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                olvideCredencialesActionPerformed(evt);
            }
        });
        jPanel2.add(olvideCredenciales, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 420, -1, -1));

        usuario.setBackground(new java.awt.Color(102, 102, 102));
        usuario.setForeground(new java.awt.Color(255, 255, 255));
        usuario.setText("Ingresa nombre de usuario");
        usuario.setBorder(null);
        usuario.setCaretColor(new java.awt.Color(255, 255, 255));
        usuario.setSelectedTextColor(new java.awt.Color(255, 255, 255));
        usuario.setSelectionColor(new java.awt.Color(255, 255, 255));
        usuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usuarioMouseClicked(evt);
            }
        });
        usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioActionPerformed(evt);
            }
        });
        jPanel2.add(usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 240, 20));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 390, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ingresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresarActionPerformed
        // TODO add your handling code here:
        String user= usuario.getText();
        String pass= new String(contraseña.getPassword());
        if(inicioSesionControl.validarUsuario(user, pass)){
            ControlPrincipal.getInstance().ocultarInicioSesion();
            ControlPrincipal.getInstance().mostrarVentanaPrincipal();
            ControlPrincipal.getInstance().mostrarUsuarioEnSesion(user);
        }
        else{
            JOptionPane mensaje= new JOptionPane();
            mensaje.setBackground(new java.awt.Color(102, 102, 102));
            mensaje.setForeground(Color.white);
            mensaje.showMessageDialog(null,"Comprueba tu usuario o contraseña");
            usuarioT.setForeground(Color.red);
            contraseñaT.setForeground(Color.red);
            contraseña.setText("");
        }
    }//GEN-LAST:event_ingresarActionPerformed

    private void usuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usuarioMouseClicked
        // TODO add your handling code here:
        usuario.setText("");
    }//GEN-LAST:event_usuarioMouseClicked

    private void usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usuarioActionPerformed

    private void olvideCredencialesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_olvideCredencialesActionPerformed
        // TODO add your handling code here:
        ControlPrincipal.getInstance().ocultarInicioSesion();
        ControlPrincipal.getInstance().mostrarVentanaRecuperacionCredenciales();
    }//GEN-LAST:event_olvideCredencialesActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new InicioSesion().setVisible(true);
//            }
//        });
//    }

    private IniciarSesionControl inicioSesionControl;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField contraseña;
    private javax.swing.JLabel contraseñaT;
    private javax.swing.JButton ingresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton olvideCredenciales;
    private javax.swing.JTextField usuario;
    private javax.swing.JLabel usuarioT;
    // End of variables declaration//GEN-END:variables
}
