/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import control.ControlPrincipal;
import control.ControlRegistroInstitucion;
import java.awt.Color;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.text.JTextComponent;

/**
 *
 * @author ferchs
 */
public class RegistroInstitucion extends javax.swing.JFrame {

    /**
     * Creates new form RegistroAdministradores
     */
    public RegistroInstitucion() {
        initComponents();
        controlRegistroInstitucion= new ControlRegistroInstitucion();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRegistro = new javax.swing.JPanel();
        nombreT = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        siguiente = new javax.swing.JButton();
        nitT = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        direccionT = new javax.swing.JLabel();
        jSeparator13 = new javax.swing.JSeparator();
        jSeparator14 = new javax.swing.JSeparator();
        emailT = new javax.swing.JLabel();
        telefonoT = new javax.swing.JLabel();
        jSeparator15 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jSeparator12 = new javax.swing.JSeparator();
        texto = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        nit = new javax.swing.JTextField();
        nombre = new javax.swing.JTextField();
        direccion = new javax.swing.JTextField();
        telefono = new javax.swing.JTextField();
        pieDePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRegistro.setBackground(new java.awt.Color(102, 102, 102));
        panelRegistro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nombreT.setBackground(new java.awt.Color(255, 255, 255));
        nombreT.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        nombreT.setForeground(new java.awt.Color(255, 255, 255));
        nombreT.setText("Nombre");
        panelRegistro.add(nombreT, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, -1, -1));

        jSeparator6.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator6.setForeground(new java.awt.Color(255, 255, 255));
        panelRegistro.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 240, -1));

        siguiente.setBackground(new java.awt.Color(101, 166, 148));
        siguiente.setForeground(new java.awt.Color(255, 255, 255));
        siguiente.setText("Siguiente");
        siguiente.setBorderPainted(false);
        siguiente.setOpaque(true);
        siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siguienteActionPerformed(evt);
            }
        });
        panelRegistro.add(siguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 520, 130, 40));

        nitT.setBackground(new java.awt.Color(255, 255, 255));
        nitT.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        nitT.setForeground(new java.awt.Color(255, 255, 255));
        nitT.setText("Nit");
        panelRegistro.add(nitT, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, -1, -1));

        jSeparator9.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator9.setForeground(new java.awt.Color(255, 255, 255));
        panelRegistro.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 240, -1));

        direccionT.setBackground(new java.awt.Color(255, 255, 255));
        direccionT.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        direccionT.setForeground(new java.awt.Color(255, 255, 255));
        direccionT.setText("Dirección");
        panelRegistro.add(direccionT, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, -1, -1));

        jSeparator13.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator13.setForeground(new java.awt.Color(255, 255, 255));
        panelRegistro.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 340, 240, -1));

        jSeparator14.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator14.setForeground(new java.awt.Color(255, 255, 255));
        panelRegistro.add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 490, 240, -1));

        emailT.setBackground(new java.awt.Color(255, 255, 255));
        emailT.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        emailT.setForeground(new java.awt.Color(255, 255, 255));
        emailT.setText("E-Mail");
        panelRegistro.add(emailT, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 440, -1, -1));

        telefonoT.setBackground(new java.awt.Color(255, 255, 255));
        telefonoT.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        telefonoT.setForeground(new java.awt.Color(255, 255, 255));
        telefonoT.setText("Teléfono");
        panelRegistro.add(telefonoT, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, -1, -1));

        jSeparator15.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator15.setForeground(new java.awt.Color(255, 255, 255));
        panelRegistro.add(jSeparator15, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 410, 240, -1));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Bienvenido!");
        panelRegistro.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, -1, -1));

        jSeparator12.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator12.setForeground(new java.awt.Color(255, 255, 255));
        panelRegistro.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 580, -1));

        texto.setBackground(new java.awt.Color(255, 255, 255));
        texto.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        texto.setForeground(new java.awt.Color(255, 255, 255));
        texto.setText("Registra los datos de tu institución:");
        panelRegistro.add(texto, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, -1, 30));

        email.setBackground(new java.awt.Color(102, 102, 102));
        email.setForeground(new java.awt.Color(255, 255, 255));
        email.setBorder(null);
        email.setCaretColor(new java.awt.Color(255, 255, 255));
        email.setSelectedTextColor(new java.awt.Color(255, 255, 255));
        email.setSelectionColor(new java.awt.Color(255, 255, 255));
        email.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                emailMouseClicked(evt);
            }
        });
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        panelRegistro.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 470, 240, 20));

        nit.setBackground(new java.awt.Color(102, 102, 102));
        nit.setForeground(new java.awt.Color(255, 255, 255));
        nit.setText("Id sin puntos (.) comas(,) o guiones(-)");
        nit.setBorder(null);
        nit.setCaretColor(new java.awt.Color(255, 255, 255));
        nit.setSelectedTextColor(new java.awt.Color(255, 255, 255));
        nit.setSelectionColor(new java.awt.Color(255, 255, 255));
        nit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nitMouseClicked(evt);
            }
        });
        nit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nitActionPerformed(evt);
            }
        });
        panelRegistro.add(nit, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 240, 20));

        nombre.setBackground(new java.awt.Color(102, 102, 102));
        nombre.setForeground(new java.awt.Color(255, 255, 255));
        nombre.setBorder(null);
        nombre.setCaretColor(new java.awt.Color(255, 255, 255));
        nombre.setSelectedTextColor(new java.awt.Color(255, 255, 255));
        nombre.setSelectionColor(new java.awt.Color(255, 255, 255));
        nombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nombreMouseClicked(evt);
            }
        });
        nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreActionPerformed(evt);
            }
        });
        panelRegistro.add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 240, 20));

        direccion.setBackground(new java.awt.Color(102, 102, 102));
        direccion.setForeground(new java.awt.Color(255, 255, 255));
        direccion.setBorder(null);
        direccion.setCaretColor(new java.awt.Color(255, 255, 255));
        direccion.setSelectedTextColor(new java.awt.Color(255, 255, 255));
        direccion.setSelectionColor(new java.awt.Color(255, 255, 255));
        direccion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                direccionMouseClicked(evt);
            }
        });
        direccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                direccionActionPerformed(evt);
            }
        });
        panelRegistro.add(direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, 240, 20));

        telefono.setBackground(new java.awt.Color(102, 102, 102));
        telefono.setForeground(new java.awt.Color(255, 255, 255));
        telefono.setBorder(null);
        telefono.setCaretColor(new java.awt.Color(255, 255, 255));
        telefono.setSelectedTextColor(new java.awt.Color(255, 255, 255));
        telefono.setSelectionColor(new java.awt.Color(255, 255, 255));
        telefono.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                telefonoMouseClicked(evt);
            }
        });
        telefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefonoActionPerformed(evt);
            }
        });
        panelRegistro.add(telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, 240, 20));

        getContentPane().add(panelRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 570));

        pieDePanel.setBackground(new java.awt.Color(101, 166, 148));
        pieDePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon("/Users/ferchs/Creative Cloud Files/websoft4.png")); // NOI18N
        pieDePanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, -1, -1));

        getContentPane().add(pieDePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 570, 580, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void siguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siguienteActionPerformed
        // TODO add your handling code here:
        if(validarEntrada()){
            int nitInstitucion= Integer.parseInt(nit.getText().replaceAll("[-+.^:,]",""));
            String nombreInstitucion=nombre.getText();
            String telefonoInstitucion=telefono.getText();
            String direccionInstitucion=direccion.getText();
            String emailInstitucion=email.getText();
            boolean registroExitoso;
            registroExitoso=controlRegistroInstitucion.registrarInstitucion(nitInstitucion, nombreInstitucion, direccionInstitucion, telefonoInstitucion, emailInstitucion);
            JOptionPane mensaje= new JOptionPane();
            if(registroExitoso){
                mensaje.setBackground(new java.awt.Color(102, 102, 102));
                mensaje.setForeground(Color.white);
                mensaje.showMessageDialog(null,"Registro exitoso");
                ControlPrincipal.getInstance().mostrarVentanaRegistroCorreo();
                ControlPrincipal.getInstance().ocultarVentanaRegistroInstitucion();
            }
            else{
                mensaje.setBackground(new java.awt.Color(102, 102, 102));
                mensaje.setForeground(Color.white);
                mensaje.showMessageDialog(null,"Registro Fallido");
                ControlPrincipal.getInstance().iniciarPrograma();
            }
        }
    }//GEN-LAST:event_siguienteActionPerformed

    public boolean validarEntrada(){
        boolean entradaValida=true;
        if(nit.getText().isEmpty()){
           mostrarEntradaErrada(nitT,nit,"Ingresa el nit de tu institucion");
           entradaValida=false;
        }
        else{
            boolean valido=true;
            try{
                Integer.parseInt(nit.getText());
                mostrarEntradaNormal(nitT,nit);
            }
            catch(Exception e){
                valido=false;
                mostrarEntradaErrada(nitT,nit,"Ingresa el nit de tu institucion");
            }
        }
        if(nombre.getText().isEmpty()){
           mostrarEntradaErrada(nombreT,nombre,"Ingresa el nombre de la institucion");
           entradaValida=false;
        }
        else{
            mostrarEntradaNormal(nombreT,nombre);
        }
        if(direccion.getText().isEmpty()){
           mostrarEntradaErrada(direccionT,direccion,"Ingresa la direccion de tu institucion");
           entradaValida=false;
        }
        else{
            mostrarEntradaNormal(direccionT,direccion);
        }
        if(telefono.getText().isEmpty()){
           mostrarEntradaErrada(telefonoT,telefono,"Ingresa el telefono de tu institucion");
           entradaValida=false;
        }
        else{
            mostrarEntradaNormal(telefonoT,telefono);
        }
        if(!email.getText().isEmpty()){
            boolean emailValido=controlRegistroInstitucion.validarEmail(email.getText());
            if(!emailValido){
              mostrarEntradaErrada(emailT,email,"E-Mail no valido");
              entradaValida=false;
            }
        }
        return entradaValida;
    }
    
    public void mostrarEntradaErrada(JLabel titulo, JTextComponent texto, String comentario){
        titulo.setForeground(Color.red);
        texto.setForeground(Color.red);
        texto.setText(comentario);
        panelRegistro.revalidate();
        panelRegistro.repaint();
    }
    
    public void mostrarEntradaNormal(JLabel titulo, JTextComponent texto){
        titulo.setForeground(Color.white);
        texto.setForeground(Color.white);
        panelRegistro.revalidate();
        panelRegistro.repaint();
    }
   

    private void emailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emailMouseClicked
        // TODO add your handling code here:
        email.setText("");
    }//GEN-LAST:event_emailMouseClicked

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void nombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nombreMouseClicked
        // TODO add your handling code here:
        nombre.setText("");
    }//GEN-LAST:event_nombreMouseClicked

    private void nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreActionPerformed

    private void direccionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_direccionMouseClicked
        // TODO add your handling code here:
        direccion.setText("");
    }//GEN-LAST:event_direccionMouseClicked

    private void direccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_direccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_direccionActionPerformed

    private void telefonoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_telefonoMouseClicked
        // TODO add your handling code here:
        telefono.setText("");
    }//GEN-LAST:event_telefonoMouseClicked

    private void telefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefonoActionPerformed

    private void nitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nitActionPerformed

    private void nitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nitMouseClicked
        // TODO add your handling code here:
        nit.setText("");
    }//GEN-LAST:event_nitMouseClicked

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(RegistroAdministradores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(RegistroAdministradores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(RegistroAdministradores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(RegistroAdministradores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new RegistroAdministradores().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField direccion;
    private javax.swing.JLabel direccionT;
    private javax.swing.JTextField email;
    private javax.swing.JLabel emailT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextField nit;
    private javax.swing.JLabel nitT;
    private javax.swing.JTextField nombre;
    private javax.swing.JLabel nombreT;
    private javax.swing.JPanel panelRegistro;
    private javax.swing.JPanel pieDePanel;
    private javax.swing.JButton siguiente;
    private javax.swing.JTextField telefono;
    private javax.swing.JLabel telefonoT;
    private javax.swing.JLabel texto;
    // End of variables declaration//GEN-END:variables
    private ControlRegistroInstitucion controlRegistroInstitucion;
}

