/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import control.ControlPrincipal;
import control.ControlVentanaPrincipal;
import javax.swing.JPanel;
import javax.swing.UIManager;

/**
 *
 * @author ferchs
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    private ControlVentanaPrincipal controlVentanaPrincipal;
    
    private JPanel actual;

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        panelFondo.setVisible(false);
        controlVentanaPrincipal= new ControlVentanaPrincipal();
        menuPanel= new MenuPanel(this);
        mostarPanel(menuPanel);
        try {
        UIManager.setLookAndFeel( UIManager.getCrossPlatformLookAndFeelClassName() );
        } 
        catch (Exception e) {
        // TODO Auto-generated catch block
         e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelUsuario = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        SalirBoton = new javax.swing.JButton();
        usuarioSesion = new javax.swing.JLabel();
        PanelLogo2 = new javax.swing.JPanel();
        PanelLogo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        PanelLogo1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        panelFondo = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 102));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelUsuario.setBackground(new java.awt.Color(102, 102, 102));
        PanelUsuario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Bienvenido");
        PanelUsuario.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        SalirBoton.setBackground(new java.awt.Color(101, 166, 148));
        SalirBoton.setForeground(new java.awt.Color(255, 255, 255));
        SalirBoton.setText("Salir");
        SalirBoton.setBorderPainted(false);
        SalirBoton.setOpaque(true);
        SalirBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirBotonActionPerformed(evt);
            }
        });
        PanelUsuario.add(SalirBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 80, 20));

        usuarioSesion.setBackground(new java.awt.Color(255, 255, 255));
        usuarioSesion.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        usuarioSesion.setForeground(new java.awt.Color(255, 255, 255));
        usuarioSesion.setText("Nombre Usuario");
        PanelUsuario.add(usuarioSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        PanelLogo2.setBackground(new java.awt.Color(101, 166, 148));
        PanelLogo2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        PanelUsuario.add(PanelLogo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 210, 10));

        getContentPane().add(PanelUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 0, 210, 110));

        PanelLogo.setBackground(new java.awt.Color(101, 166, 148));
        PanelLogo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon("/Users/ferchs/Creative Cloud Files/WebSoft3.png")); // NOI18N
        PanelLogo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 300, 100));

        PanelLogo1.setBackground(new java.awt.Color(101, 166, 148));
        PanelLogo1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon("/Users/ferchs/Creative Cloud Files/WebSoft3.png")); // NOI18N
        PanelLogo1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 300, 100));

        PanelLogo.add(PanelLogo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 110));

        getContentPane().add(PanelLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 110));

        panelFondo.setBackground(new java.awt.Color(102, 102, 102));
        getContentPane().add(panelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 880, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SalirBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirBotonActionPerformed
        // TODO add your handling code here:
       controlVentanaPrincipal.salirAplicacion();
    }//GEN-LAST:event_SalirBotonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
              ControlPrincipal.getInstance().iniciarPrograma();
            }
        });
    }
    
    public void mostarMenu(){
        mostarPanel(menuPanel);
    }
    
    public void mostarPanel(JPanel panel){
        panelFondo.setVisible(true);
        if(actual!=null){
            getContentPane().remove(actual);
            pack();
        }
        actual=panel;
        getContentPane().add(panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 880, 580));
        panelFondo.setVisible(false);
        getContentPane().revalidate();
        getContentPane().repaint();
        pack();
    }
    
    private void agregarPaneles(){
//        menuPanel= new MenuPanel(this);
//        estudiantesPanel= new EstudiantesPanel();
//        profesoresPanel= new ProfesoresPanel();
//        reportesPanel= new ReportesPanel();
//        menuPanel.setVisible(true);
//        estudiantesPanel.setVisible(false);
//        profesoresPanel.setVisible(false);
//        reportesPanel.setVisible(false);
//        getContentPane().add(menuPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 880, 550));
//        getContentPane().add(estudiantesPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 880, 550));
//        getContentPane().add(profesoresPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 880, 550));
//        getContentPane().add(reportesPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 880, 550));
////        PanelOpciones.revalidate();
////        PanelOpciones.repaint();
//        pack();
    }
    
    public void seleccionarTap(String tap){
//       if(tap.equals("estudiantes")){
//           estudiantesPanel.setVisible(true);
//           menuPanel.setVisible(false);
//       }
//       if(tap.equals("profesores")){
//           profesoresPanel.setVisible(true);
//           menuPanel.setVisible(false);
//       }
//       if(tap.equals("reportes")){
//           reportesPanel.setVisible(true);
//           estudiantesPanel.setVisible(false);
//           profesoresPanel.setVisible(false);
//       }
//       if(tap.equals("principal")){
//           menuPanel.setVisible(true);
//       }
    }
    
    public void mostrarUsuarioEnSesion(String nombreUsuario){
        usuarioSesion.setText(nombreUsuario.toUpperCase());
    }
    
    private MenuPanel menuPanel;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelLogo;
    private javax.swing.JPanel PanelLogo1;
    private javax.swing.JPanel PanelLogo2;
    private javax.swing.JPanel PanelUsuario;
    private javax.swing.JButton SalirBoton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel panelFondo;
    private javax.swing.JLabel usuarioSesion;
    // End of variables declaration//GEN-END:variables
}

